import { createEnv } from '@t3-oss/env-core';
import { z } from 'zod';

const optionalString = z.string().optional();

const server = {
  AI_PROVIDER_ATTEMPT_ADMISSION_MODE: optionalString,
  AI_PROVIDER_ATTEMPT_ADMISSION_POLICIES_JSON: optionalString,
  AI_PROVIDER_MODEL: optionalString,
  AI_PROVIDER_OVERRIDE: optionalString,
  AI_PROVIDER_SESSION_ADMISSION_MODE: optionalString,
  AI_PROVIDER_SESSION_ADMISSION_POLICIES_JSON: optionalString,
  AI_RATE_LIMIT_MAX: optionalString,
  AI_RATE_LIMIT_WINDOW_MS: optionalString,
  ANTHROPIC_API_KEY: optionalString,
  ANTHROPIC_AUTH_TOKEN: optionalString,
  ANTHROPIC_BASE_URL: optionalString,
  API_PORT: optionalString,
  API_SMOKE_BASE_URL: optionalString,
  AUTO_INTERVENTION_EXPANSION_ENABLED: optionalString,
  BACKUP_IMPORT_MAX_BYTES: optionalString,
  B3_GATE_CONFIRM_CLONE: optionalString,
  CLAUDE_CODE_OAUTH_TOKEN: optionalString,
  CONFUSABLE_CONTRAST_ENABLED: optionalString,
  COPILOT_NUDGE_DAILY_MAX: optionalString,
  COPILOT_NUDGE_ENABLED: optionalString,
  COPILOT_NUDGE_EXPIRES_HOURS: optionalString,
  COPILOT_NUDGE_KC_COOLDOWN_HOURS: optionalString,
  COPILOT_NUDGE_STREAK_N: optionalString,
  COPILOT_SUBAGENT_ENABLED: optionalString,
  DASHSCOPE_API_KEY: optionalString,
  DATABASE_URL: z.string().url(),
  DOCKER_HOST: optionalString,
  DOCX_CONVERT_ENGINE: optionalString.transform((value) =>
    value === 'docker' ? value : undefined,
  ),
  EXTRACT_OCR_ENGINE: z.enum(['glm', 'tencent']).optional(),
  HUB_SYNC_MODE: optionalString,
  INTERNAL_TOKEN: optionalString,
  INTERVENTION_DISABLED_METHOD_IDS: optionalString,
  JUDGE_DURABLE_ENABLED: optionalString,
  JUDGE_CALIBRATION_BATCH_MAX: optionalString,
  JUDGE_CALIBRATION_REJUDGE_MODEL: optionalString,
  JUDGE_CALIBRATION_REJUDGE_PROVIDER: optionalString,
  JUDGE_CALIBRATION_SAMPLING_ENABLED: optionalString,
  JUDGE_CALIBRATION_WINDOW_DAYS: optionalString,
  JUDGE_FALLBACK_PROVIDER: optionalString,
  JUDGE_PROVENANCE_SECRET: optionalString,
  JYEOO_FETCH_ENABLED: optionalString,
  JYEOO_RS_BINARY: optionalString,
  KC_DEDUP_DISTANCE_MAX: optionalString,
  KC_DEDUP_MAX_PAIRS: optionalString,
  KC_DEDUP_WINDOW_DAYS: optionalString,
  LOCAL_NEXT_PORT: optionalString,
  LOCAL_POSTGRES_HOST: optionalString,
  LOCAL_POSTGRES_PORT: optionalString,
  MEMORY_RECONCILE_HANDOFF_MODE: optionalString,
  MEM0_EMBEDDING_BASE_URL: optionalString,
  MEM0_EMBEDDING_DIMS: optionalString,
  MEM0_EMBEDDING_MODEL: optionalString,
  MEM0_HISTORY_DB_PATH: optionalString,
  MEM0_LLM_BASE_URL: optionalString,
  MEM0_LLM_MODEL: optionalString,
  MEM0_PGVECTOR_COLLECTION: optionalString,
  MEM0_PGVECTOR_DISKANN: optionalString,
  MEM0_PGVECTOR_HNSW: optionalString,
  MEM0_TELEMETRY: optionalString,
  MIMO_VISION_BASE_URL: optionalString,
  MIMO_VISION_MODEL: optionalString,
  MISCONCEPTION_HARD_CONFIRM_ENABLED: optionalString,
  MISCONCEPTION_PROMOTE_ENABLED: optionalString,
  NODE_ENV: optionalString,
  OPENAI_API_KEY: optionalString,
  OPENROUTER_API_KEY: optionalString,
  PLACEMENT_PROBE_ENABLED: optionalString,
  POSTGRES_DB: optionalString,
  POSTGRES_PASSWORD: optionalString,
  POSTGRES_USER: optionalString,
  PROFILE_CRITIC_OK: optionalString,
  PROJECTION_IS_WRITER: optionalString,
  PROJECTION_IS_WRITER_ARTIFACT: optionalString,
  PROJECTION_IS_WRITER_GOAL: optionalString,
  PROJECTION_IS_WRITER_ITEM_CALIBRATION: optionalString,
  PROJECTION_IS_WRITER_LEARNING_ITEM: optionalString,
  PROJECTION_IS_WRITER_MISTAKE_VARIANT: optionalString,
  PROJECTION_IS_WRITER_QUESTION_BLOCK: optionalString,
  QUESTION_SUPPLY_REFILL_ENABLED: optionalString,
  RESEARCH_MEETING_AGENT_ENABLED: optionalString,
  R2_ACCESS_KEY_ID: optionalString,
  R2_BUCKET: optionalString,
  R2_ENDPOINT: z.string().url().optional(),
  R2_SECRET_ACCESS_KEY: optionalString,
  RW_STATIC_DIR: optionalString,
  RW_WORKER: optionalString,
  SEED_SYNTHETIC_OK: optionalString,
  SELECTION_POLICY: optionalString,
  SKIP_BOSS_INGEST: optionalString,
  TAGGING_MATCH_THRESHOLD: optionalString,
  TAVILY_API_KEY: optionalString,
  TENCENT_OCR_REGION: optionalString,
  TENCENT_SECRET_ID: optionalString,
  TENCENT_SECRET_KEY: optionalString,
  TUNNEL_PROTOCOL: optionalString,
  TUNNEL_TOKEN: optionalString,
  VERCEL_AI_GATEWAY_TOKEN: optionalString,
  VERIFY_SOLVE_MODEL_OVERRIDE: optionalString,
  VERIFY_SOLVE_PROVIDER_OVERRIDE: optionalString,
  VISION_JUDGE_MODEL: optionalString,
  VISION_JUDGE_PROVIDER: optionalString,
  VITEST: optionalString,
  WAVE6_TRIGGER_DREAMING_ENABLED: optionalString,
  WAVE6_TRIGGER_MARK_WRONG_ENABLED: optionalString,
  WAVE6_TRIGGER_MASTERY_ENABLED: optionalString,
  WAVE6_TRIGGER_VERIFY_ENABLED: optionalString,
  WORKFLOW_JUDGE_AUTO_ENROLL_ENABLED: optionalString,
  WORKFLOW_JUDGE_AUTO_ENROLL_THRESHOLD: optionalString,
  WORKFLOW_JUDGE_OBSERVE_ENABLED: optionalString,
  WORKFLOW_JUDGE_STUDENT_ANSWER_GRADING_ENABLED: optionalString,
  XIAOMI_API_KEY: optionalString,
  ZHIPU_API_KEY: optionalString,
};

export const SERVER_ENV_KEYS: ReadonlySet<string> = new Set(Object.keys(server));

export function createServerEnv(
  runtimeEnv: Record<string, string | undefined> = process.env,
  skipValidation = Boolean(runtimeEnv.VITEST),
) {
  return createEnv({
    server,
    runtimeEnv,
    skipValidation,
    emptyStringAsUndefined: true,
  });
}

export function getServerEnv(): ReturnType<typeof createServerEnv> {
  return createServerEnv();
}

export function requireApiInternalToken(
  runtimeEnv: Record<string, string | undefined> = process.env,
): string {
  return z
    .string({ error: 'INTERNAL_TOKEN is required for the API' })
    .min(1, 'INTERNAL_TOKEN is required for the API')
    .parse(runtimeEnv.INTERNAL_TOKEN);
}
