import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { configDefaults } from 'vitest/config';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const resolveConfig = {
  alias: { '@': path.resolve(__dirname, 'src') },
};

// YUK-279 — single source of truth for the JSX transform both vitest configs
// share. tsconfig has `jsx: "preserve"` (Next transforms JSX at build), so vitest
// must transform JSX itself via esbuild's automatic runtime; otherwise component
// tests crash with `React is not defined`. Both the unit and db configs import
// this so the transform can never drift between the two partitions.
// YUK-315 (2026-06-10) — vite 8 起 JS 转换引擎为 Rolldown/Oxc：`esbuild` 配置项在
// vitest 链路下不再生效（tsconfig jsx:preserve 的 JSX 无人转换 → .tsx 测试 parse
// 失败），等价物为 oxc.jsx（runtime automatic，同语义）。legacy 单 config
//（vitest.config.ts，pnpm test:legacy）如需 .tsx 同样换 oxc。
export const sharedOxc = {
  jsx: { runtime: 'automatic' },
} as const;

// YUK-1401: reviewed invariant files only. New tests must be explicitly assigned.
export const fastTestInclude = [
  'src/capabilities/ingestion/server/reference-origin.unit.test.ts',
  'scripts/api-smoke.test.ts',
  'scripts/cutover-backup.test.ts',
  'scripts/migration-apply.test.ts',
  'scripts/migration-capture-ssl.test.ts',
  'scripts/migration-capture.test.ts',
  'server/app.unit.test.ts',
  'server/start/auth.unit.test.ts',
  'src/capabilities/agency/server/meeting/director-tools.unit.test.ts',
  'src/capabilities/copilot/server/subagents.unit.test.ts',
  'src/capabilities/copilot/server/tool-activity.unit.test.ts',
  'src/capabilities/copilot/server/tool-result-snapshot.unit.test.ts',
  'src/capabilities/ingestion/server/assessment-review-evidence.unit.test.ts',
  'src/capabilities/observability/api/backup-import.unit.test.ts',
  'src/capabilities/practice/server/fsrs.unit.test.ts',
  'src/capabilities/practice/server/judge/evaluation-authority.unit.test.ts',
  'src/capabilities/practice/server/judge/keyword.test.ts',
  'src/capabilities/practice/server/judge/multimodal-direct-judge.test.ts',
  'src/capabilities/practice/server/judge/preview-provenance-token.test.ts',
  'src/capabilities/practice/server/judge/steps-judge.test.ts',
  'src/capabilities/practice/server/question-supply/jyeoo-spawn.test.ts',
  'src/capabilities/practice/server/quiz/verify-framework.test.ts',
  'src/capabilities/practice/server/rating-advisor.unit.test.ts',
  'src/capabilities/practice/tasks/evaluation-policy-routing.unit.test.ts',
  'src/core/capability/judges/exact.test.ts',
  'src/core/capability/judges/unit_dimension.test.ts',
  'src/core/capability/judges/unit_dimension/accelerator.test.ts',
  'src/core/capability/judges/unit_dimension/score.test.ts',
  'src/core/coldstart-solver-parity.unit.test.ts',
  'src/core/coldstart-solver.unit.test.ts',
  'src/core/graph-laplacian.test.ts',
  'src/core/migration/apply.test.ts',
  'src/core/migration/classify.test.ts',
  'src/core/migration/redact.test.ts',
  'src/core/net/private-host.unit.test.ts',
  'src/core/pfa.test.ts',
  'src/core/poly-exp-parity.unit.test.ts',
  'src/core/poly-exp.unit.test.ts',
  'src/core/prereq-propagation.test.ts',
  'src/core/schema/assessment/evaluation.test.ts',
  'src/core/schema/assessment/scoring.test.ts',
  'src/core/schema/assessment/settlement.test.ts',
  'src/core/theta-grid.test.ts',
  'src/core/theta.test.ts',
  'src/server/ai/laminar-tracing.test.ts',
  'src/server/ai/laminar-transcript.test.ts',
  'src/server/ai/pi-agent-adapter.tracing.test.ts',
  'src/server/ai/runner.stream-collect.test.ts',
  'src/server/ai/tools/mcp-bridge.test.ts',
  'src/server/assessment/jev-model-executor.test.ts',
  'src/server/calibration/native-parity.unit.test.ts',
  'src/server/calibration/replay.unit.test.ts',
  'src/server/calibration/wasm-parity.unit.test.ts',
  'src/server/http/errors.test.ts',
  'src/server/memory/client.test.ts',
  'src/server/memory/provider-operation.test.ts',
  'src/server/projections/parity.unit.test.ts',
];

export const dbTestInclude = [
  'server/start/admin-control-reader.db.test.ts',
  'server/start/admin-reader.db.test.ts',
  'src/capabilities/agency/api/probe-answer.db.test.ts',
  'src/capabilities/agency/jobs/research_meeting_closed_loop.db.test.ts',
  'src/capabilities/agency/server/conjecture-accept.db.test.ts',
  'src/capabilities/agency/server/conjecture/probe-lifecycle.db.test.ts',
  'src/capabilities/agency/server/goals/queries.db.test.ts',
  'src/capabilities/agency/server/goals/scope.db.test.ts',
  'src/capabilities/agency/server/intervention/intervention-preparation.db.test.ts',
  'src/capabilities/agency/server/meeting/director.db.test.ts',
  'src/capabilities/agency/server/misconception-promote.db.test.ts',
  'src/capabilities/agency/server/proposal-appliers.db.test.ts',
  'src/capabilities/copilot/api/cancel-run.db.test.ts',
  'src/capabilities/copilot/api/nudges.db.test.ts',
  'src/capabilities/copilot/api/revert-checkpoint.db.test.ts',
  'src/capabilities/copilot/api/review-answer.db.test.ts',
  'src/capabilities/copilot/jobs/copilot_nudge_evaluate.db.test.ts',
  'src/capabilities/copilot/jobs/copilot_run.streaming.db.test.ts',
  'src/capabilities/copilot/jobs/copilot_run.teaching.db.test.ts',
  'src/capabilities/copilot/jobs/copilot_run.test.ts',
  'src/capabilities/copilot/jobs/copilot_run_reconcile.db.test.ts',
  'src/capabilities/copilot/server/durable-dispatch.db.test.ts',
  'src/capabilities/copilot/server/durable-session-queue.db.test.ts',
  'src/capabilities/copilot/server/skills/teaching-skill.db.test.ts',
  'src/capabilities/copilot/server/subagent-mailbox.db.test.ts',
  'src/capabilities/copilot/server/tool-result-snapshot.db.test.ts',
  'src/capabilities/copilot/server/turns.db.test.ts',
  'src/capabilities/ingestion/api/asset-delete.db.test.ts',
  'src/capabilities/ingestion/api/assets.db.test.ts',
  'src/capabilities/ingestion/api/import.db.test.ts',
  'src/capabilities/ingestion/jobs/tencent_ocr_extract.concurrency.db.test.ts',
  'src/capabilities/ingestion/server/assessment-capture.db.test.ts',
  'src/capabilities/ingestion/server/assessment-review.db.test.ts',
  'src/capabilities/ingestion/server/auto-enroll.db.test.ts',
  'src/capabilities/ingestion/server/make-paper.db.test.ts',
  'src/capabilities/ingestion/server/operation-store.db.test.ts',
  'src/capabilities/ingestion/server/proposal-appliers.db.test.ts',
  'src/capabilities/ingestion/server/provider-attempts.db.test.ts',
  'src/capabilities/ingestion/server/revert-auto-enroll.db.test.ts',
  'src/capabilities/ingestion/server/tools/question-block-edits.db.test.ts',
  'src/capabilities/knowledge/api/misconception-veto.db.test.ts',
  'src/capabilities/knowledge/jobs/kc_dedup_nightly.db.test.ts',
  'src/capabilities/knowledge/jobs/knowledge_maintenance_nightly.db.test.ts',
  'src/capabilities/knowledge/jobs/merge_attribution_sweep.db.test.ts',
  'src/capabilities/knowledge/jobs/projection_oracle_sweep.db.test.ts',
  'src/capabilities/knowledge/server/edges.db.test.ts',
  'src/capabilities/knowledge/server/misconception-edges.db.test.ts',
  'src/capabilities/knowledge/server/proposals.db.test.ts',
  'src/capabilities/knowledge/server/seed.db.test.ts',
  'src/capabilities/notes/api/hub-dismiss-link.db.test.ts',
  'src/capabilities/notes/jobs/note_verify.db.test.ts',
  'src/capabilities/notes/server/block-refs.db.test.ts',
  'src/capabilities/notes/server/hub-sync-reconciliation.db.test.ts',
  'src/capabilities/notes/server/mastery-progress-subscription.db.test.ts',
  'src/capabilities/notes/server/note-handoff-boss-contract.db.test.ts',
  'src/capabilities/notes/server/note-handoff.db.test.ts',
  'src/capabilities/notes/server/sections.db.test.ts',
  'src/capabilities/observability/api/_round_trip.db.test.ts',
  'src/capabilities/observability/api/admin-config-write.db.test.ts',
  'src/capabilities/observability/api/admin-config.db.test.ts',
  'src/capabilities/observability/api/restore_column_allowlist.db.test.ts',
  'src/capabilities/observability/server/subject-control-operations.db.test.ts',
  'src/capabilities/observability/server/trait-control-operations.db.test.ts',
  'src/capabilities/practice/api/placement-native.db.test.ts',
  'src/capabilities/practice/api/question-detail-write.db.test.ts',
  'src/capabilities/practice/api/question-detail.db.test.ts',
  'src/capabilities/practice/api/review-sessions.db.test.ts',
  'src/capabilities/practice/api/session-resources.db.test.ts',
  'src/capabilities/practice/api/stream.db.test.ts',
  'src/capabilities/practice/api/submit-durable-resource.db.test.ts',
  'src/capabilities/practice/api/submit-late-arrival.db.test.ts',
  'src/capabilities/practice/api/submit-native-calibration.db.test.ts',
  'src/capabilities/practice/api/submit-native-diagnostic.db.test.ts',
  'src/capabilities/practice/jobs/attribution_followup.db.test.ts',
  'src/capabilities/practice/jobs/judge_pending_reconcile.db.test.ts',
  'src/capabilities/practice/jobs/judge_run.db.test.ts',
  'src/capabilities/practice/jobs/jyeoo_staged_asset_reap.db.test.ts',
  'src/capabilities/practice/jobs/quiz_gen.test.ts',
  'src/capabilities/practice/jobs/quiz_verify.test.ts',
  'src/capabilities/practice/jobs/rejudge.db.test.ts',
  'src/capabilities/practice/jobs/source_verify.test.ts',
  'src/capabilities/practice/server/assessment/material-recovery.db.test.ts',
  'src/capabilities/practice/server/assessment/submission-persistence.db.test.ts',
  'src/capabilities/practice/server/cause-overlay.db.test.ts',
  'src/capabilities/practice/server/compose-paid-work-lock.db.test.ts',
  'src/capabilities/practice/server/evaluate-submission.db.test.ts',
  'src/capabilities/practice/server/failure-learning-attribution.db.test.ts',
  'src/capabilities/practice/server/failure-learning-subscription.db.test.ts',
  'src/capabilities/practice/server/failure-learning-variant.db.test.ts',
  'src/capabilities/practice/server/judge-calibration-sample.db.test.ts',
  'src/capabilities/practice/server/mastery-progress-signal.db.test.ts',
  'src/capabilities/practice/server/merge-attribution.db.test.ts',
  'src/capabilities/practice/server/native-durable-attempt.db.test.ts',
  'src/capabilities/practice/server/paper-adaptation.db.test.ts',
  'src/capabilities/practice/server/paper-cycle.db.test.ts',
  'src/capabilities/practice/server/paper-issuance.db.test.ts',
  'src/capabilities/practice/server/paper-mastery-progress.db.test.ts',
  'src/capabilities/practice/server/paper-submit-session-race.db.test.ts',
  'src/capabilities/practice/server/placement-starter-recovery.db.test.ts',
  'src/capabilities/practice/server/proposal-appliers.db.test.ts',
  'src/capabilities/practice/server/question-supply/placement-starter-attempts.db.test.ts',
  'src/capabilities/practice/server/question-supply/placement-starter-store.db.test.ts',
  'src/capabilities/practice/server/quiz/content-fingerprint.db.test.ts',
  'src/capabilities/practice/server/recorded-model-executor.db.test.ts',
  'src/capabilities/practice/server/review-operation.db.test.ts',
  'src/capabilities/practice/server/review-settlement.db.test.ts',
  'src/capabilities/practice/server/solve-session-media.db.test.ts',
  'src/capabilities/practice/server/stream-store-provider-lock.db.test.ts',
  'src/capabilities/practice/server/stream-store-reserved-connection.db.test.ts',
  'src/capabilities/practice/server/stream-store.db.test.ts',
  'src/capabilities/practice/server/tools/get-attempt-context.test.ts',
  'src/capabilities/practice/server/tools/store-sourced-question.db.test.ts',
  'src/capabilities/practice/server/tools/write-quiz.test.ts',
  'src/capabilities/shell/api/proposal-decisions.db.test.ts',
  'src/capabilities/shell/api/teaching-brief-ack.db.test.ts',
  'src/capabilities/shell/api/teaching-brief-interaction.db.test.ts',
  'src/capabilities/shell/server/teaching-brief-issuance.db.test.ts',
  'src/kernel/events/events.db.test.ts',
  'src/kernel/tools/tool-operations.db.test.ts',
  'src/server/advisory-locks.db.test.ts',
  'src/server/ai/provider-attempt-lifecycle.db.test.ts',
  'src/server/ai/provider-session-admission.db.test.ts',
  'src/server/ai/solution-generate.test.ts',
  'src/server/ai/tools/author-question.test.ts',
  'src/server/ai/tools/propose-question-edit.db.test.ts',
  'src/server/ai/tools/read-tools-m2.test.ts',
  'src/server/artifacts/presence/pg.db.test.ts',
  'src/server/assessment/activate.db.test.ts',
  'src/server/assessment/admission.db.test.ts',
  'src/server/assessment/joint-input.db.test.ts',
  'src/server/assessment/settle.db.test.ts',
  'src/server/boss/handlers/ai_task_run_reconcile.db.test.ts',
  'src/server/boss/verify-dispatch-outbox.db.test.ts',
  'src/server/calibration/replay.fixture.db.test.ts',
  'src/server/conjectures/reconcile.db.test.ts',
  'src/server/conjectures/typed-state.db.test.ts',
  'src/server/contract-epoch/epoch.db.test.ts',
  'src/server/boss/handlers/prune-assessment-review.db.test.ts',
  'src/server/durable/producer-fence-lock.db.test.ts',
  'src/server/durable/review-orphan-family.db.test.ts',
  'src/server/durable/session-orphan-family.db.test.ts',
  'src/server/event-subscriptions/runtime.db.test.ts',
  'src/server/export/assessment-contract-backup.db.test.ts',
  'src/server/export/intervention-backup.db.test.ts',
  'src/server/export/mem0-collection-backup.db.test.ts',
  'src/server/export/provider-attempt-backup.db.test.ts',
  'src/server/export/subscription-backup.db.test.ts',
  'src/server/mastery/fixed-anchor.db.test.ts',
  'src/server/mastery/item-calibration.db.test.ts',
  'src/server/mastery/kt-calibration.db.test.ts',
  'src/server/mastery/personalized-difficulty.db.test.ts',
  'src/server/mastery/recalibration.db.test.ts',
  'src/server/mastery/retire-state-on-merge.db.test.ts',
  'src/server/mastery/state.db.test.ts',
  'src/server/memory/conjecture-projection.db.test.ts',
  'src/server/memory/mem0-sdk-failure.db.test.ts',
  'src/server/memory/memory-ingest-recovery.db.test.ts',
  'src/server/memory/memory-reconcile-handoff-handler.db.test.ts',
  'src/server/memory/memory-reconcile-handoff.db.test.ts',
  'src/server/memory/provider-operation-fence.db.test.ts',
  'src/server/memory/reconcile-handler.db.test.ts',
  'src/server/memory/triggers.outbox.test.ts',
  'src/server/migration/apply.db.test.ts',
  'src/server/migration/capture.db.test.ts',
  'src/server/orchestration/orchestrator.db.test.ts',
  'src/server/projections/canonical-migration.db.test.ts',
  'src/server/projections/knowledge-history-migration.db.test.ts',
  'src/server/projections/learning_item.db.test.ts',
  'src/server/projections/materialized-id-index.db.test.ts',
  'src/server/projections/normalize-edge-created-by.db.test.ts',
  'src/server/projections/parity-writers-c3.db.test.ts',
  'src/server/proposals/actions.test.ts',
  'src/server/proposals/edge-decide-advisory-lock.db.test.ts',
  'src/server/proposals/retract-clock.db.test.ts',
  'src/server/proposals/signals.test.ts',
  'src/server/questions/publisher.db.test.ts',
  'src/server/questions/question-generation-grounding.db.test.ts',
  'src/server/questions/write-restore.db.test.ts',
  'src/server/records/native-mistake-evidence.db.test.ts',
  'src/server/records/queries.test.ts',
  'src/server/rehearsal/rehearsal.db.test.ts',
  'src/server/revert/cascade-revert.db.test.ts',
  'src/server/session/conversation-orphan.db.test.ts',
  'src/server/session/placement-orphan.db.test.ts',
  'src/server/session/review-orphan.db.test.ts',
  'src/server/subjects/hydrate.db.test.ts',
  'src/server/subjects/subject-control-write.db.test.ts',
  'src/server/subjects/thin-create.db.test.ts',
  'tests/dbos-prune/cron.db.test.ts',
  'tests/dbos-prune/migration.db.test.ts',
  'tests/dbos-review-orphan/cron.db.test.ts',
  'tests/dbos-review-orphan/migration.db.test.ts',
  'tests/dbos-session-orphan/cron.db.test.ts',
  'tests/dbos-session-orphan/migration.db.test.ts',
  'tests/integration/config-hot-reload.db.test.ts',
  'tests/integration/config-restore-epoch.db.test.ts',
  'tests/integration/config-write-boundaries.db.test.ts',
  'tests/integration/item_prior_backfill.db.test.ts',
  'tests/integration/native-pi-config-migration.db.test.ts',
  'tests/integration/restore-snapshot.db.test.ts',
  'tests/integration/scope-mode-0063-datafix.db.test.ts',
  'tests/restore-parity/canonical.db.test.ts',
];

export const migrationSmokeInclude = ['tests/integration/migration-smoke.test.ts'];

export const allTestInclude = [...fastTestInclude, ...dbTestInclude, ...migrationSmokeInclude];

export const sharedExclude = configDefaults.exclude;
