import type { AdminReadClient } from '@/capabilities/observability/ui/admin-client';

const usage = {
  inputTokens: 12000,
  outputTokens: 987,
  source: { alternatives: [null, 'reported'] },
};
export const adminRun = {
  id: 'run-unknown-first',
  task_kind: 'EvidenceAnalysis',
  provider: 'test',
  model: 'fixture',
  input_hash: 'hash:original',
  status: 'failure',
  finish_reason: 'tool_error',
  usage_json: usage,
  cost_usd: null,
  cost_basis: 'unknown',
  cost_ref: 'unpriced:fixture',
  error_message: '证据有歧义与长文本。\n'.repeat(80),
  started_at: '2026-10-08T02:00:00.123Z',
  finished_at: '2026-10-08T02:00:01.456Z',
  duration_ms: 1333,
  ledger_cost_usd: null,
  ledger_rows: 2,
  tool_call_count: 1,
  pgboss_job_ids: ['job-original'],
} satisfies Awaited<ReturnType<AdminReadClient['getRuns']>>['rows'][number];
const runRows = [
  adminRun,
  {
    ...adminRun,
    id: 'run-running-second',
    task_kind: 'RunningTask',
    status: 'running',
    finished_at: null,
    duration_ms: null,
    finish_reason: null,
    error_message: null,
    cost_usd: 0,
  },
];
export const adminRuns = {
  rows: runRows,
  data: runRows,
  page: { limit: 100, next_cursor: 'opaque-cursor' },
  limit: 100,
  next_cursor: 'opaque-cursor',
  total: 170,
  truncated: true,
} satisfies Awaited<ReturnType<AdminReadClient['getRuns']>>;
export const adminDetail = {
  run: adminRun,
  ledger: [
    {
      id: 'ledger-unknown',
      task_run_id: adminRun.id,
      task_kind: adminRun.task_kind,
      provider: 'test',
      model: 'fixture',
      cost: null,
      currency: 'CNY',
      entry_kind: 'attempt',
      cost_basis: 'unknown',
      cost_ref: null,
      tokens_in: 12000,
      tokens_out: 987,
      outcome: 'failure',
      pgboss_job_id: null,
      occurred_at: '2026-10-08T02:00:00.789Z',
    },
  ],
  tool_calls: [
    {
      id: 'tool-original',
      tool_name: 'read_evidence',
      iteration: 3,
      latency_ms: 123.5,
      cost: 0,
      occurred_at: '2026-10-08T02:00:00.500Z',
    },
  ],
  timeline: [
    { type: 'run_started', at: adminRun.started_at, label: 'EvidenceAnalysis' },
    {
      type: 'tool_call',
      id: 'tool-original',
      at: '2026-10-08T02:00:00.500Z',
      label: 'read_evidence',
      tool_name: 'read_evidence',
      iteration: 3,
      latency_ms: 123.5,
      cost: 0,
    },
    {
      type: 'cost_ledger',
      id: 'ledger-unknown',
      at: '2026-10-08T02:00:00.789Z',
      label: 'failure',
      cost_basis: 'unknown',
      cost_ref: null,
      outcome: 'failure',
      tokens_in: 12000,
      tokens_out: 987,
      pgboss_job_id: null,
    },
    {
      type: 'run_finished',
      at: '2026-10-08T02:00:01.456Z',
      label: 'failure',
      outcome: 'tool_error',
    },
  ],
} satisfies Awaited<ReturnType<AdminReadClient['getRunDetail']>>;
const usdCost = {
  currency: 'USD',
  cost: 0.75,
  reported_cost: 0.5,
  estimated_cost: 0.25,
  legacy_cost: 0,
  reported_attempts: 2,
  estimated_attempts: 1,
  legacy_rows: 0,
  unknown_attempts: 3,
  tokens_in: 10000,
  tokens_out: 500,
  calls: 6,
};
const cnyCost = {
  ...usdCost,
  currency: 'CNY',
  cost: 0,
  reported_cost: 0,
  estimated_cost: 0,
  reported_attempts: 1,
  estimated_attempts: 0,
  unknown_attempts: 1,
  calls: 2,
};
export const adminCost = {
  days_window: 30,
  days: [
    { day: '2026-10-08', ...usdCost },
    { day: '2026-10-08', ...cnyCost },
  ],
  by_task: [
    { task_kind: 'EvidenceAnalysis', ...usdCost },
    { task_kind: 'RunningTask', ...cnyCost },
  ],
  by_truth: [
    {
      currency: 'USD',
      entry_kind: 'attempt',
      cost_basis: 'unknown',
      cost_ref: null,
      cost: 0,
      tokens_in: 10000,
      tokens_out: 500,
      calls: 3,
      unknown_attempts: 3,
    },
  ],
} satisfies Awaited<ReturnType<AdminReadClient['getCost']>>;
export const adminFailures = {
  limit: 200,
  clusters: [
    {
      key: 'tool_error:Ambiguous evidence',
      finish_reason: 'tool_error',
      error_prefix: 'Ambiguous evidence',
      count: 7,
      latest_at: adminRun.started_at,
      samples: [
        {
          id: adminRun.id,
          task_kind: adminRun.task_kind,
          model: adminRun.model,
          started_at: adminRun.started_at,
          error_message: adminRun.error_message,
        },
      ],
    },
  ],
} satisfies Awaited<ReturnType<AdminReadClient['getFailures']>>;
export const adminCoverage = {
  generated_at: '2026-10-08T02:03:00.123Z',
  scan_ms: 23,
  coverage_depth_threshold: 3,
  near_window: 0.5,
  cooldown_days: 7,
  scope_note: 'scanCoverageGaps 四规则；未评估不是完整覆盖',
  subjects: [
    {
      subjectId: 'math',
      displayName: '数学',
      kcs: [
        {
          knowledgeId: 'kc-ambiguous',
          thetaHat: 0.2,
          evidenceCount: 2,
          usableCount: 0,
          depthMet: false,
          hasHighTier: null,
          hasNearThetaAnchor: null,
          formatDiverse: null,
          gapKinds: ['frontier_zero'],
          gaps: [
            {
              gapKind: 'frontier_zero',
              kind: 'mcq',
              difficultyBand: 'near',
              minSourceTier: 2,
              desiredCount: 3,
              priority: 0.75,
              reason: '保留未评估和歧义条件'.repeat(30),
              fingerprint: 'fingerprint-original',
              routePreference: ['author_question'],
              scaffold: true,
              lastActivity: {
                lastActivityAt: '2026-10-07T02:00:00.000Z',
                lastStatus: 'failed',
                lastDispatchedAt: null,
                inCooldown: true,
                cooldownUntil: '2026-10-14T02:00:00.000Z',
              },
            },
          ],
        },
      ],
    },
  ],
  totals: { activeKcs: 1, kcsWithGaps: 1, totalGaps: 1, gapsByKind: { frontier_zero: 1 } },
} satisfies Awaited<ReturnType<AdminReadClient['getCoverage']>>;
export const adminConjectures = {
  score_basis: 'single_point',
  prediction_scores: [
    {
      event_id: 'score-original',
      conjecture_event_id: 'conjecture-original',
      probe_result_event_id: 'probe-original',
      knowledge_id: 'kc-ambiguous',
      predicted_p: 0.7,
      baseline_p: 0.5,
      outcome: 0,
      resolution: 'evidence_for',
      brier_model: 0.49,
      brier_baseline: 0.25,
      log_loss_model: null,
      skill_score_point: null,
      retrievability_at_judge: null,
      created_at: '2026-10-08T02:00:00.123Z',
    },
  ],
  typed_states: [
    {
      id: 'typed-original',
      knowledge_id: 'kc-ambiguous',
      typed_state: 'confused-with-X',
      confused_with_kc_id: 'kc-other',
      lifecycle: 'open',
      evidence_event_ids: ['probe-original', 'failure-original'],
      last_evidence_at: null,
      updated_at: '2026-10-08T02:01:00.456Z',
    },
  ],
  diagnostics: {
    prediction_scores: { scanned_count: 501, dropped_count: 2, scan_truncated: true },
    typed_states: { scanned_count: 3, dropped_count: 1, scan_truncated: false },
  },
} satisfies Awaited<ReturnType<AdminReadClient['getConjectureScores']>>;
