/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AgentNotesRouteImport } from './routes/agent-notes'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as TodayRouteImport } from './routes/today'
import { Route as BuildSplatRouteImport } from './routes/[_]build.$'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminConjectureScoresRouteImport } from './routes/admin.conjecture-scores'
import { Route as AdminCostRouteImport } from './routes/admin.cost'
import { Route as AdminCoverageLatticeRouteImport } from './routes/admin.coverage-lattice'
import { Route as AdminFailuresRouteImport } from './routes/admin.failures'
import { Route as AdminRunsRouteImport } from './routes/admin.runs'
import { Route as AdminSubjectsRouteImport } from './routes/admin.subjects'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AdminSubjectsIdRouteImport } from './routes/admin.subjects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentNotesRoute = AgentNotesRouteImport.update({
  id: '/agent-notes',
  path: '/agent-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildSplatRoute = BuildSplatRouteImport.update({
  id: '/_build/$',
  path: '/_build/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConjectureScoresRoute = AdminConjectureScoresRouteImport.update({
  id: '/admin/conjecture-scores',
  path: '/admin/conjecture-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCostRoute = AdminCostRouteImport.update({
  id: '/admin/cost',
  path: '/admin/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoverageLatticeRoute = AdminCoverageLatticeRouteImport.update({
  id: '/admin/coverage-lattice',
  path: '/admin/coverage-lattice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFailuresRoute = AdminFailuresRouteImport.update({
  id: '/admin/failures',
  path: '/admin/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRunsRoute = AdminRunsRouteImport.update({
  id: '/admin/runs',
  path: '/admin/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsRoute = AdminSubjectsRouteImport.update({
  id: '/admin/subjects',
  path: '/admin/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubjectsIdRoute = AdminSubjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSubjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agent-notes': typeof AgentNotesRoute
  '/inbox': typeof InboxRoute
  '/mistakes': typeof MistakesRoute
  '/today': typeof TodayRoute
  '/_build/$': typeof BuildSplatRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/conjecture-scores': typeof AdminConjectureScoresRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/coverage-lattice': typeof AdminCoverageLatticeRoute
  '/admin/failures': typeof AdminFailuresRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/subjects': typeof AdminSubjectsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/subjects/$id': typeof AdminSubjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agent-notes': typeof AgentNotesRoute
  '/inbox': typeof InboxRoute
  '/mistakes': typeof MistakesRoute
  '/today': typeof TodayRoute
  '/_build/$': typeof BuildSplatRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/conjecture-scores': typeof AdminConjectureScoresRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/coverage-lattice': typeof AdminCoverageLatticeRoute
  '/admin/failures': typeof AdminFailuresRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/subjects': typeof AdminSubjectsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/subjects/$id': typeof AdminSubjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agent-notes': typeof AgentNotesRoute
  '/inbox': typeof InboxRoute
  '/mistakes': typeof MistakesRoute
  '/today': typeof TodayRoute
  '/_build/$': typeof BuildSplatRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/conjecture-scores': typeof AdminConjectureScoresRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/coverage-lattice': typeof AdminCoverageLatticeRoute
  '/admin/failures': typeof AdminFailuresRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/subjects': typeof AdminSubjectsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/events/$id': typeof EventsIdRoute
  '/admin/subjects/$id': typeof AdminSubjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/agent-notes'
    | '/inbox'
    | '/mistakes'
    | '/today'
    | '/_build/$'
    | '/admin/config'
    | '/admin/conjecture-scores'
    | '/admin/cost'
    | '/admin/coverage-lattice'
    | '/admin/failures'
    | '/admin/runs'
    | '/admin/subjects'
    | '/api/$'
    | '/events/$id'
    | '/admin/subjects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/agent-notes'
    | '/inbox'
    | '/mistakes'
    | '/today'
    | '/_build/$'
    | '/admin/config'
    | '/admin/conjecture-scores'
    | '/admin/cost'
    | '/admin/coverage-lattice'
    | '/admin/failures'
    | '/admin/runs'
    | '/admin/subjects'
    | '/api/$'
    | '/events/$id'
    | '/admin/subjects/$id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/agent-notes'
    | '/inbox'
    | '/mistakes'
    | '/today'
    | '/_build/$'
    | '/admin/config'
    | '/admin/conjecture-scores'
    | '/admin/cost'
    | '/admin/coverage-lattice'
    | '/admin/failures'
    | '/admin/runs'
    | '/admin/subjects'
    | '/api/$'
    | '/events/$id'
    | '/admin/subjects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AgentNotesRoute: typeof AgentNotesRoute
  InboxRoute: typeof InboxRoute
  MistakesRoute: typeof MistakesRoute
  TodayRoute: typeof TodayRoute
  BuildSplatRoute: typeof BuildSplatRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminConjectureScoresRoute: typeof AdminConjectureScoresRoute
  AdminCostRoute: typeof AdminCostRoute
  AdminCoverageLatticeRoute: typeof AdminCoverageLatticeRoute
  AdminFailuresRoute: typeof AdminFailuresRoute
  AdminRunsRoute: typeof AdminRunsRoute
  AdminSubjectsRoute: typeof AdminSubjectsRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  EventsIdRoute: typeof EventsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-notes': {
      id: '/agent-notes'
      path: '/agent-notes'
      fullPath: '/agent-notes'
      preLoaderRoute: typeof AgentNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_build/$': {
      id: '/_build/$'
      path: '/_build/$'
      fullPath: '/_build/$'
      preLoaderRoute: typeof BuildSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conjecture-scores': {
      id: '/admin/conjecture-scores'
      path: '/admin/conjecture-scores'
      fullPath: '/admin/conjecture-scores'
      preLoaderRoute: typeof AdminConjectureScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cost': {
      id: '/admin/cost'
      path: '/admin/cost'
      fullPath: '/admin/cost'
      preLoaderRoute: typeof AdminCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coverage-lattice': {
      id: '/admin/coverage-lattice'
      path: '/admin/coverage-lattice'
      fullPath: '/admin/coverage-lattice'
      preLoaderRoute: typeof AdminCoverageLatticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/failures': {
      id: '/admin/failures'
      path: '/admin/failures'
      fullPath: '/admin/failures'
      preLoaderRoute: typeof AdminFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/runs': {
      id: '/admin/runs'
      path: '/admin/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects': {
      id: '/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subjects/$id': {
      id: '/admin/subjects/$id'
      path: '/$id'
      fullPath: '/admin/subjects/$id'
      preLoaderRoute: typeof AdminSubjectsIdRouteImport
      parentRoute: typeof AdminSubjectsRoute
    }
  }
}

interface AdminSubjectsRouteChildren {
  AdminSubjectsIdRoute: typeof AdminSubjectsIdRoute
}

const AdminSubjectsRouteChildren: AdminSubjectsRouteChildren = {
  AdminSubjectsIdRoute: AdminSubjectsIdRoute,
}

const AdminSubjectsRouteWithChildren = AdminSubjectsRoute._addFileChildren(
  AdminSubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AgentNotesRoute: AgentNotesRoute,
  InboxRoute: InboxRoute,
  MistakesRoute: MistakesRoute,
  TodayRoute: TodayRoute,
  BuildSplatRoute: BuildSplatRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminConjectureScoresRoute: AdminConjectureScoresRoute,
  AdminCostRoute: AdminCostRoute,
  AdminCoverageLatticeRoute: AdminCoverageLatticeRoute,
  AdminFailuresRoute: AdminFailuresRoute,
  AdminRunsRoute: AdminRunsRoute,
  AdminSubjectsRoute: AdminSubjectsRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  EventsIdRoute: EventsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
