/* Loom v2 — SEED data shaped as ADR-0006 v2 events.
   3 tables (in spirit): material, learning_session, event.
   This is just enough to make all 6 routes feel like a live system.

   Conventions:
   - event ids are e_NN, monotonic-ish
   - caused_by_event_id chains DAG
   - timestamps in unix seconds, anchored to NOW
*/

const NOW = Math.floor(Date.now() / 1000);
const MIN = 60, HR = 3600, DAY = 86400;

// ── material · knowledge ───────────────────────────────────
const KNOWLEDGE = [
  { id: 'k_wenyan',     name: '文言文',        parent_id: null,        depth: 0 },
  { id: 'k_xuci',       name: '文言虚词',      parent_id: 'k_wenyan',  depth: 1 },
  { id: 'k_xuci_zhi',   name: '之 (用法)',     parent_id: 'k_xuci',    depth: 2 },
  { id: 'k_xuci_zhi_attr', name: '之·定语标志', parent_id: 'k_xuci_zhi', depth: 3, proposed: true },
  { id: 'k_xuci_yu',    name: '于 (用法)',     parent_id: 'k_xuci',    depth: 2 },
  { id: 'k_xuci_er',    name: '而 (用法)',     parent_id: 'k_xuci',    depth: 2 },
  { id: 'k_shici',      name: '实词词义',      parent_id: 'k_wenyan',  depth: 1 },
  { id: 'k_juedu',      name: '断句',          parent_id: 'k_wenyan',  depth: 1 },
  { id: 'k_fanyi',      name: '翻译',          parent_id: 'k_wenyan',  depth: 1 },
];

// ── material · question ────────────────────────────────────
const QUESTIONS = {
  q1: {
    id: 'q1',
    prompt_md: '"之"在「古之学者必有师」中的用法是？',
    reference_md: '结构助词，定语标志，相当于「的」。',
    knowledge_ids: ['k_xuci_zhi'],
    source: { doc: '《师说》', page: 'p.1' },
  },
  q2: {
    id: 'q2',
    prompt_md: '翻译：「师者，所以传道受业解惑也」。',
    reference_md: '老师，是用来传授道理、教授学业、解答疑惑的人。',
    knowledge_ids: ['k_juedu', 'k_shici', 'k_fanyi'],
    source: { doc: '《师说》', page: 'p.1' },
  },
  q3: {
    id: 'q3',
    prompt_md: '「青，取之于蓝，而青于蓝」中两个"于"的用法？',
    reference_md: '前一个表来源(从)；后一个表比较(比)。',
    knowledge_ids: ['k_xuci_yu'],
    source: { doc: '《劝学》', page: 'p.3' },
  },
  q4: {
    id: 'q4',
    prompt_md: '「逝者如斯夫」中的"夫"应理解为？',
    reference_md: '语气助词，表感叹，相当于「啊」。',
    knowledge_ids: ['k_xuci'],
    source: { doc: '《论语·子罕》', page: '九年级 上' },
  },
  // variant generated by AI from q1
  q1v1: {
    id: 'q1v1',
    prompt_md: '辨析下列三句中"之"的用法：① 古之学者　② 蚓无爪牙之利　③ 句读之不知',
    reference_md: '① 助词，定语标志（的）　② 助词，定语后置标志　③ 助词，宾语前置标志',
    knowledge_ids: ['k_xuci_zhi'],
    source: { doc: 'AI 变式', page: '由 q1 派生' },
    derived_from: 'q1',
  },
};

// ── material · artifact ────────────────────────────────────
// AI-generated content lives here. Created by `action='generate'`.
const ARTIFACTS = {
  a_v_q1_1: {
    id: 'a_v_q1_1', kind: 'variant',
    title: '变式 1 · 三句辨析「之」',
    body_md: '辨析下列三句中"之"的用法：① 古之学者　② 蚓无爪牙之利　③ 句读之不知',
    question_id: 'q1v1',
  },
  a_n_zhi: {
    id: 'a_n_zhi', kind: 'note',
    title: '之 · 用法小结',
    body_md: '助词"之"的四种用法：① 定语标志（的）② 宾语前置标志 ③ 定语后置标志 ④ 用在主谓之间取消句子独立性。代词"之"指代前文出现的人/事/物。',
  },
  a_v_q3_1: {
    id: 'a_v_q3_1', kind: 'variant',
    title: '变式 1 · 三个"于"',
    body_md: '解释「夫人之相与，俯仰一世」「青取之于蓝」「冰，水为之而寒于水」中三个不同的"于"。',
  },
  a_q_xuci_zhi: {
    id: 'a_q_xuci_zhi', kind: 'quiz',
    title: '小测 · 之 vs 其',
    body_md: '5 题选择，对比"之"作助词与"其"作代词的语境。',
  },
};

// ── learning_session ──────────────────────────────────────
const SESSIONS = {
  s_ingest_now: {
    id: 's_ingest_now', type: 'ingestion', status: 'extracting',
    started_at: NOW - 12 * MIN, title: '语文练习册 p.45-46',
  },
  s_review_now: {
    id: 's_review_now', type: 'review', status: 'active',
    started_at: NOW - 4 * MIN,
  },
  s_dream_last_night: {
    id: 's_dream_last_night', type: 'ingestion', status: 'completed',
    started_at: NOW - 7 * HR, ended_at: NOW - 5 * HR, title: 'Dreaming 夜间扫描',
  },
  s_copilot: {
    id: 's_copilot', type: 'conversation', status: 'active',
    started_at: NOW - 2 * MIN, title: 'Copilot · 关于 q1',
  },
};

// ── event · the spine ─────────────────────────────────────
const EVENTS = [
  // ── Scenario 1: user wrong-answered q1 yesterday, AI ran the chain ──
  {
    id: 'e_01', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'attempt',
    subject_kind: 'question', subject_id: 'q1', outcome: 'failure',
    payload: { answer_md: '代词，指代「学者」。', duration_ms: 28400 },
    caused_by_event_id: null,
    created_at: NOW - DAY,
  },
  {
    id: 'e_02', session_id: null,
    actor_kind: 'agent', actor_ref: 'attribution', action: 'judge',
    subject_kind: 'event', subject_id: 'e_01', outcome: 'success',
    payload: {
      cause: {
        primary: 'concept', confidence: 0.87,
        ai_analysis_md: '把结构助词「之」误识为代词。下意识把"古之学者"翻译成 "学者古" → 倒推认为「之」指代「学者」。实际上「之」在此为定语标志（的）。',
        referenced_knowledge_ids: ['k_xuci_zhi'],
        actor_kind: 'agent',
      },
    },
    caused_by_event_id: 'e_01',
    task_run_id: 't_001', cost_micro_usd: 4200,
    created_at: NOW - DAY + 14,
  },
  {
    id: 'e_03', session_id: null,
    actor_kind: 'agent', actor_ref: 'variant_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_v_q1_1', outcome: 'success',
    payload: {
      artifact_kind: 'variant',
      title: '变式 1 · 三句辨析「之」',
      body_md: '辨析下列三句中"之"的用法：① 古之学者　② 蚓无爪牙之利　③ 句读之不知',
      referenced_event_ids: ['e_01'],
    },
    caused_by_event_id: 'e_02',
    task_run_id: 't_002', cost_micro_usd: 18600,
    created_at: NOW - DAY + 32,
  },
  {
    id: 'e_04', session_id: null,
    actor_kind: 'agent', actor_ref: 'propose', action: 'propose',
    subject_kind: 'knowledge', subject_id: 'k_xuci_zhi_attr', outcome: 'success',
    payload: {
      name: '之 · 定语标志',
      parent_id: 'k_xuci_zhi',
      reasoning: '错答 e_01 的归因结论 = 没区分助词与代词。建议为「之 (用法)」加一个细分子节点，专门聚焦"定语标志"这一最易混淆的子用法。',
    },
    caused_by_event_id: 'e_02',
    task_run_id: 't_003', cost_micro_usd: 12000,
    created_at: NOW - DAY + 48,
  },
  {
    id: 'e_05', session_id: null,
    actor_kind: 'agent', actor_ref: 'note_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_n_zhi', outcome: 'success',
    payload: {
      artifact_kind: 'note',
      title: '之 · 用法小结',
      body_md: ARTIFACTS.a_n_zhi.body_md,
    },
    caused_by_event_id: 'e_02',
    task_run_id: 't_004', cost_micro_usd: 9800,
    created_at: NOW - DAY + 70,
  },

  // ── Scenario 2: q2 wrong-answer 2 days ago, AI judged ──
  {
    id: 'e_10', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'attempt',
    subject_kind: 'question', subject_id: 'q2', outcome: 'failure',
    payload: { answer_md: '老师所以传授道理、学业和解答疑惑。', duration_ms: 52000 },
    caused_by_event_id: null,
    created_at: NOW - 2 * DAY,
  },
  {
    id: 'e_11', session_id: null,
    actor_kind: 'agent', actor_ref: 'attribution', action: 'judge',
    subject_kind: 'event', subject_id: 'e_10', outcome: 'success',
    payload: {
      cause: {
        primary: 'expression', confidence: 0.74,
        ai_analysis_md: '理解正确但表述卡在"所以"的现代汉语化。「所以」在此=「用来…的（人）」，是名词性结构，不能直接套现代"所以"。',
        referenced_knowledge_ids: ['k_shici', 'k_fanyi'],
        actor_kind: 'agent',
      },
    },
    caused_by_event_id: 'e_10',
    task_run_id: 't_010', cost_micro_usd: 4400,
    created_at: NOW - 2 * DAY + 18,
  },

  // ── Scenario 3: q3 wrong-answered 1 hour ago — judge is in-flight ──
  {
    id: 'e_20', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'attempt',
    subject_kind: 'question', subject_id: 'q3', outcome: 'failure',
    payload: { answer_md: '都表示比较。', duration_ms: 19200 },
    caused_by_event_id: null,
    created_at: NOW - 12 * MIN,
  },
  // judge pending (no e_21 yet)

  // ── Scenario 4: nightly Dreaming agent (cron) — last night ──
  {
    id: 'e_30', session_id: 's_dream_last_night',
    actor_kind: 'cron', actor_ref: 'nightly_dreaming', action: 'experimental:trigger_dreaming_scan',
    subject_kind: 'event', subject_id: 's_dream_last_night', outcome: null,
    payload: {}, caused_by_event_id: null,
    created_at: NOW - 7 * HR,
  },
  {
    id: 'e_31', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'dreaming', action: 'experimental:scan',
    subject_kind: 'knowledge', subject_id: 'k_xuci_zhi', outcome: 'success',
    payload: { notes: '最近 5 次错答有 3 次落在「之」上' },
    caused_by_event_id: 'e_30',
    task_run_id: 't_030', cost_micro_usd: 8200,
    created_at: NOW - 7 * HR + 3 * MIN,
  },
  {
    id: 'e_32', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'variant_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_v_q3_1', outcome: 'success',
    payload: {
      artifact_kind: 'variant',
      title: '变式 1 · 三个"于"',
      body_md: ARTIFACTS.a_v_q3_1.body_md,
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_031', cost_micro_usd: 16800,
    created_at: NOW - 7 * HR + 6 * MIN,
  },
  {
    id: 'e_33', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'note_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_q_xuci_zhi', outcome: 'success',
    payload: {
      artifact_kind: 'quiz',
      title: '小测 · 之 vs 其',
      body_md: ARTIFACTS.a_q_xuci_zhi.body_md,
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_032', cost_micro_usd: 11400,
    created_at: NOW - 7 * HR + 9 * MIN,
  },
  {
    id: 'e_34', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'dreaming', action: 'propose',
    subject_kind: 'knowledge', subject_id: 'k_xuci_er', outcome: 'success',
    payload: {
      name: '而 · 转折 vs 并列',
      parent_id: 'k_xuci_er',
      reasoning: '当前 k_xuci_er 节点尚未拆分子用法，但用户最近 3 次"而"题目均答错于"转折/并列"识别。',
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_033', cost_micro_usd: 7200,
    created_at: NOW - 7 * HR + 11 * MIN,
  },
  {
    id: 'e_35', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'critique', action: 'experimental:critique',
    subject_kind: 'event', subject_id: 'e_32', outcome: 'failure',
    payload: { reason: '变式与原题"于"的难度梯度太陡，建议先出一个 2 选 1 的判断题再上升级。' },
    caused_by_event_id: 'e_32',
    task_run_id: 't_034', cost_micro_usd: 5600,
    created_at: NOW - 7 * HR + 14 * MIN,
  },

  // ── Reviews (FSRS) ────────────────────────────────────────
  {
    id: 'e_40', session_id: 's_review_now',
    actor_kind: 'user', actor_ref: 'self', action: 'review',
    subject_kind: 'question', subject_id: 'q4', outcome: 'success',
    payload: { fsrs_rating: 'good', fsrs_state_after: { due: NOW + 3 * DAY, stability: 4.2, state: 'review' } },
    caused_by_event_id: null,
    created_at: NOW - 4 * MIN,
  },
  {
    id: 'e_41', session_id: 's_review_now',
    actor_kind: 'user', actor_ref: 'self', action: 'review',
    subject_kind: 'question', subject_id: 'q2', outcome: 'failure',
    payload: { fsrs_rating: 'hard', fsrs_state_after: { due: NOW + 6 * HR, stability: 1.2, state: 'learning' } },
    caused_by_event_id: null,
    created_at: NOW - 2 * MIN,
  },

  // ── Ingestion (current SSE feed) ──────────────────────────
  {
    id: 'e_50', session_id: 's_ingest_now',
    actor_kind: 'user', actor_ref: 'self', action: 'import',
    subject_kind: 'source_document', subject_id: 'sd_001', outcome: 'success',
    payload: { filename: 'paper-p45.jpg', size_kb: 2840 },
    created_at: NOW - 12 * MIN,
  },
  {
    id: 'e_51', session_id: 's_ingest_now',
    actor_kind: 'agent', actor_ref: 'tencent_mark', action: 'extract',
    subject_kind: 'source_document', subject_id: 'sd_001', outcome: 'partial',
    payload: { layout_quality: 'partial', warnings: ['cloze 5 空 / 检出 3 sub'], structured_block_ids: ['b1','b2','b3'] },
    caused_by_event_id: 'e_50',
    task_run_id: 't_050', cost_micro_usd: 0,
    created_at: NOW - 10 * MIN,
  },

  // ── Rate events: user accepted note a_n_zhi yesterday ─────
  {
    id: 'e_60', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'rate',
    subject_kind: 'event', subject_id: 'e_05', outcome: 'success',
    payload: { rating: 'accept', user_note: '收藏，挺有用' },
    caused_by_event_id: null,
    created_at: NOW - 22 * HR,
  },
];

// ── learning_item — TODO/Goal layer, decoupled from event ──
const LEARNING_ITEMS = [
  { id: 'li1', title: '梳理「之」的所有用法',     knowledge_ids: ['k_xuci_zhi'],        status: 'in_progress', version: 2, created_at: NOW - 3 * DAY, source: 'user' },
  { id: 'li2', title: '把《师说》全文背下来',     knowledge_ids: ['k_juedu', 'k_shici'], status: 'pending',     version: 1, created_at: NOW - 5 * DAY, source: 'user' },
  { id: 'li3', title: '「于」的来源 vs 比较',     knowledge_ids: ['k_xuci_yu'],          status: 'done',        version: 3, created_at: NOW - 14 * DAY, completed_at: NOW - 7 * DAY, source: 'user' },
  { id: 'li4', title: '攻克"而"的转折/并列判别', knowledge_ids: ['k_xuci_er'],          status: 'pending',     version: 1, created_at: NOW - 6 * HR,  source: 'agent', proposed_by: 'dreaming' },
];

// ── Sample copilot conversation events for s_copilot ───────
// These are mounted as messages in the Copilot drawer; user can drive further.
const COPILOT_SEED_EVENTS = [
  {
    id: 'ec_01', session_id: 's_copilot',
    actor_kind: 'user', actor_ref: 'self', action: 'experimental:ask_copilot',
    subject_kind: 'event', subject_id: 'e_01', outcome: null,
    payload: { text: '为什么这里"之"是定语标志？不能理解为代词吗？' },
    caused_by_event_id: 'e_01',
    created_at: NOW - 100,
  },
  {
    id: 'ec_02', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:explain',
    subject_kind: 'event', subject_id: 'ec_01', outcome: 'success',
    payload: {
      text_md: '"古之学者必有师" 字面顺序倒装回现代汉语，是 "古的学者一定有老师"。这里 "之" 把后面的名词 "学者" 修饰成前面 "古" 的所有物——这就是定语标志（"的"）。\n\n要判断"之"是助词还是代词，最快的方法是把它代换成"的"读一遍：能通就是助词，不通就再考虑代词。',
      referenced_knowledge_ids: ['k_xuci_zhi'],
    },
    caused_by_event_id: 'ec_01',
    task_run_id: 't_c01', cost_micro_usd: 3600,
    created_at: NOW - 88,
  },
];

// Convenience: index events by id, by subject
function indexEvents(events) {
  const byId = {};
  const childrenOf = {}; // caused_by_event_id → [child events]
  const bySubject = {};  // `${kind}:${id}` → [events]
  for (const ev of events) {
    byId[ev.id] = ev;
    if (ev.caused_by_event_id) {
      (childrenOf[ev.caused_by_event_id] ||= []).push(ev);
    }
    const sk = `${ev.subject_kind}:${ev.subject_id}`;
    (bySubject[sk] ||= []).push(ev);
  }
  return { byId, childrenOf, bySubject };
}

Object.assign(window, {
  NOW, MIN, HR, DAY,
  KNOWLEDGE, QUESTIONS, ARTIFACTS, SESSIONS,
  EVENTS, LEARNING_ITEMS, COPILOT_SEED_EVENTS,
  indexEvents,
});
