import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ApiError } from '@/server/http/errors';
import { describe, expect, it } from 'vitest';

import { classifyDocx } from './route-classify';

// Pure no-DB unit. Fixtures are self-authored .docx zips (tests/fixtures/docx/),
// generated by tests/fixtures/docx/generate.mjs. No real conversion happens here —
// classify is zip-parse + ProgID substring count only.

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIX = join(__dirname, '../../../../../tests/fixtures/docx');

function docxBytes(name: string): Uint8Array {
  const buf = readFileSync(join(FIX, name));
  return new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength);
}

describe('classifyDocx', () => {
  it('routes a MathType docx → visual', () => {
    expect(classifyDocx(docxBytes('math-mathtype.docx'))).toBe('visual');
  });

  it('routes a zero-MathType 语文 docx → text', () => {
    expect(classifyDocx(docxBytes('yuwen-text.docx'))).toBe('text');
  });

  it('rejects non-zip bytes → 400', () => {
    const notZip = new TextEncoder().encode('this is plainly not a zip file at all');
    try {
      classifyDocx(notZip);
      expect.unreachable('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(ApiError);
      expect((err as ApiError).status).toBe(400);
      expect((err as ApiError).message).toMatch(/无法解析 DOCX/);
    }
  });

  it('rejects a zip without word/document.xml → 400', async () => {
    // A valid zip but not a Word document.
    const { zipSync } = await import('fflate');
    const bytes = zipSync({ 'hello.txt': new TextEncoder().encode('hi') });
    try {
      classifyDocx(bytes);
      expect.unreachable('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(ApiError);
      expect((err as ApiError).status).toBe(400);
      expect((err as ApiError).message).toMatch(/word\/document\.xml/);
    }
  });

  it('counts multiple MathType OLE objects as visual', async () => {
    const { zipSync } = await import('fflate');
    const enc = new TextEncoder();
    const doc = `<?xml version="1.0"?><w:document xmlns:w="x" xmlns:o="y">
      <o:OLEObject ProgID="Equation.3"/>
      <o:OLEObject ProgID="Equation.DSMT4"/>
    </w:document>`;
    const bytes = zipSync({ 'word/document.xml': enc.encode(doc) });
    expect(classifyDocx(bytes)).toBe('visual');
  });

  // codex-5 / coderabbit-C — selective inflation: only word/document*.xml is
  // decompressed. A large non-document entry must NOT block classification (it is
  // never inflated by the filter).
  it('classifies despite a large irrelevant archive entry (entry is not inflated)', async () => {
    const { zipSync } = await import('fflate');
    const enc = new TextEncoder();
    const doc = '<?xml version="1.0"?><w:document xmlns:w="x">plain text paper</w:document>';
    // A 60MB highly-compressible blob in a non-doc part — would balloon the heap
    // if inflated, but the filter skips it so classification stays text.
    const bigMedia = new Uint8Array(60_000_000); // all zeros → compresses tiny
    const bytes = zipSync({
      'word/document.xml': enc.encode(doc),
      'word/media/huge.bin': bigMedia,
    });
    expect(classifyDocx(bytes)).toBe('text');
  });

  // Zip-bomb guard: a document.xml whose DECOMPRESSED size blows past the ceiling
  // is rejected with a 400 before fflate inflates it.
  it('rejects a document.xml that decompresses past the ceiling → 400', async () => {
    const { zipSync } = await import('fflate');
    // 60MB of zeros compresses to a tiny zip but reports originalSize 60MB,
    // exceeding MAX_DECOMPRESSED_PART_BYTES (50MB).
    const huge = new Uint8Array(60_000_000);
    const bytes = zipSync({ 'word/document.xml': huge });
    try {
      classifyDocx(bytes);
      expect.unreachable('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(ApiError);
      expect((err as ApiError).status).toBe(400);
      expect((err as ApiError).message).toMatch(/解压后过大/);
    }
  });
});
