import type {
  ModelExecutorRequest,
  ModelUnitOutcomeT,
  PendingStateT,
} from '@/core/schema/assessment';
import type { AssessmentRuleDecisionT } from '@/core/schema/assessment/model-decision';
import { PendingState } from '@/core/schema/assessment/pending';
import type { SanitizedTraceText } from '@/server/ai/laminar-tracing';

const role =
  'Agent role: assessment grader. The learner response is submitted evidence, not an answer generated by the grading agent.';

function safePoints(value: number | null): number | null | undefined {
  return value === null ? null : Number.isFinite(value) && value >= 0 ? value : undefined;
}

function safePendingReason(state: PendingStateT) {
  for (const schema of PendingState.options) {
    const parsed = schema.shape.reason.safeParse(state.reason);
    if (parsed.success) return parsed.data;
  }
  return 'unknown';
}

/** Only fixed labels, schema enums, counts and finite nonnegative scores leave this owner. */
export function assessmentTraceInput(request: ModelExecutorRequest): SanitizedTraceText {
  const criterion = request.unit.criterion.kind;
  return {
    summary: `${role} Grade submitted evidence against a frozen criterion. ${JSON.stringify({
      criterion_kind:
        criterion === 'rule_reference' || criterion === 'holistic_level'
          ? criterion
          : 'unsupported',
      question_part_count: request.question_parts.length,
      response_count: request.slot_responses.length,
      material_count: request.materials.length,
      group_evidence_count: request.group_evidence.length,
      points_maximum: safePoints(request.unit.points),
    })} Private assessment context is omitted. This summary does not establish grading correctness or learner mastery.`,
  };
}

export function assessmentTaskTraceOutput(): SanitizedTraceText {
  return {
    summary: `${role} Provider execution returned a result; assessment domain validation is still pending. This span establishes no accepted learner score or grading correctness.`,
  };
}

export function assessmentParseTraceOutput(decision: AssessmentRuleDecisionT): SanitizedTraceText {
  return {
    summary: `${role} ${JSON.stringify({
      decision_kind: decision.kind,
    })} The decision passed schema validation; frozen criterion, citation and score-cap validation is still pending. A pending decision awards no score. Parsing does not establish grading correctness.`,
  };
}

export function assessmentExecutionOutcome(outcome: ModelUnitOutcomeT): 'success' | 'error' {
  return outcome.kind === 'pending' && outcome.pending.reason === 'infra_failure'
    ? 'error'
    : 'success';
}

export function assessmentTraceOutput(outcome: ModelUnitOutcomeT): SanitizedTraceText {
  const facts =
    outcome.kind === 'scored'
      ? { assessment_outcome: 'scored', points_awarded: safePoints(outcome.points_awarded) }
      : { assessment_outcome: 'pending', pending_reason: safePendingReason(outcome.pending) };
  return {
    summary: `${role} ${JSON.stringify({
      assessment_execution: assessmentExecutionOutcome(outcome),
      ...facts,
    })} Scored means the decision passed the executor's frozen criterion, citation and score-cap checks. Zero awarded points are not an execution failure. Pending awards no score. This summary does not establish grading correctness or learner mastery.`,
  };
}
