// Test-only response fixture. No browser/runtime imports.
import type { ConfigData, ConfigTask } from './config-model';
export function configFixture(): ConfigData {
  const task: ConfigTask = {
    kind: 'QuizGenTask',
    default_provider: 'xiaomi',
    default_model: 'mimo-v2.5-pro',
    default_budget: { maxIterations: 6, maxCost: 0.5, timeout: 60_000, transientRetries: 0 },
    effective_budget: { maxIterations: 6, maxCost: null, timeout: 60_000, transientRetries: 0 },
    budget_wiring: { maxIterations: true, maxCost: false, timeout: true, transientRetries: true },
    budget_note: '费用上限未接线；重试还受调用策略限制。',
    override: null,
    override_wired: { provider: true, model: true, budget: false },
    global_pin: null,
    effective_binding: { provider: 'xiaomi', model: 'mimo-v2.5-pro', error: null },
  };
  return {
    snapshot: { epoch: 4, hydrated_at: '2026-10-04T04:00:00Z' },
    facts_injected: true,
    keys: [
      {
        key: 'locale.learner',
        value: 'zh-CN',
        default: 'zh-CN',
        effective: 'zh-CN',
        source: 'code-default',
        env_mode: 'fallback',
        env_name: null,
        tier: 'B',
        read_only: false,
        wired: true,
        consumer: 'src/ai/task-prompts.ts',
        revision: null,
        updated_at: null,
      },
      {
        key: 'PLACEMENT_PROBE_ENABLED',
        value: true,
        default: true,
        effective: true,
        source: 'compose-forced',
        env_mode: 'pinned',
        env_name: 'PLACEMENT_PROBE_ENABLED',
        tier: 'A',
        read_only: true,
        wired: true,
        consumer: 'src/capabilities/practice/server/placement.ts',
        revision: null,
        updated_at: null,
      },
    ],
    tasks: [
      task,
      {
        ...task,
        kind: 'JevScoringDecisionTask',
        default_provider: 'openrouter',
        default_model: 'jev',
        override_wired: { provider: false, model: false, budget: false },
        budget_wiring: {
          maxIterations: false,
          maxCost: true,
          timeout: true,
          transientRetries: true,
        },
        effective_binding: { provider: 'openrouter', model: 'jev', error: null },
      },
    ],
    providers: [
      {
        name: 'xiaomi',
        pi_provider: 'xiaomi',
        auth_mode: 'key',
        credential_env: 'XIAOMI_API_KEY',
        key_present: true,
        implemented: true,
        models: [
          { id: 'mimo-v2.5-pro', api: 'openai-completions', input: ['text'] },
          { id: 'mimo-v2.5', api: 'openai-completions', input: ['text', 'image'] },
        ],
      },
      {
        name: 'opencode-go',
        pi_provider: 'opencode-go',
        auth_mode: 'key',
        credential_env: 'OPENCODE_API_KEY',
        key_present: true,
        implemented: true,
        models: [{ id: 'glm-5.3-flash', api: 'openai-completions', input: ['text'] }],
      },
      {
        name: 'anthropic-sub',
        pi_provider: 'anthropic',
        auth_mode: 'oauth',
        credential_env: 'CLAUDE_CODE_OAUTH_TOKEN',
        key_present: false,
        implemented: true,
        models: [{ id: 'claude-opus-4-8', api: 'anthropic-messages', input: ['text', 'image'] }],
      },
      {
        name: 'openrouter',
        pi_provider: null,
        auth_mode: 'key',
        credential_env: 'OPENROUTER_API_KEY',
        key_present: true,
        implemented: false,
        implemented_for: { chat: false, typed: true },
        models: [],
      },
    ],
    schedules: {
      read_only_note: '只读调度声明，不代表任务已执行。',
      rows: [
        {
          name: 'maintenance',
          cron: '0 4 * * *',
          tz: 'Asia/Shanghai',
          owner: 'agency',
          queue: 'maintenance',
          source: 'capability-manifest',
        },
      ],
    },
    runtime: null,
  };
}
