import type { ToolExecutionResultObservation } from '@/server/ai/tools/mcp-bridge';

/**
 * Production-contract fixture copied from the five-case Xiaomi burn-in at
 * revision a5c1e42e (results SHA-256
 * fbcf4eb85593294a4b503f2b49052b21ec523ac4c06ab589c37fd3bb1f99f4ab).
 *
 * It deliberately retains complete query_events/get_attempt_context/get_review_due
 * inputs and typed outputs instead of a hand-written miniature schema. The six
 * observations carry A03 sibling/noncausal support, A04 B/C projection
 * asymmetry, and C04 exact-zero versus review/future-queue boundaries.
 */
export const REALISTIC_EVIDENCE_TRACE = [
  {
    name: 'get_attempt_context',
    effect: 'read',
    input: {
      causalLimit: 10,
      timelineLimit: 10,
      attemptEventId: 'conjecture_yuk792_canary_20260731c',
    },
    output: {
      cause: null,
      lookup: {
        status: 'unsupported_event',
        observed: {
          action: 'experimental:proposal',
          outcome: 'partial',
          event_id: 'conjecture_yuk792_canary_20260731c',
          evidence: {
            kind: 'proposal',
            target: {
              subject_id: 'kc_yuk792_canary_20260731c',
              subject_kind: 'mind_model',
            },
            conjecture: {
              knowledge_id: 'kc_yuk792_canary_20260731c',
              claim_present: true,
              probe_quality: {
                passed: true,
                attempt_count: 1,
                schema_version: 3,
              },
              cause_category: 'concept_misunderstanding',
              discriminating: true,
              corrected_by_owner: false,
              recurrence_gate_satisfied: true,
              diagnostic_contract_present: true,
              primary_probe_contract_present: true,
              followup_probe_contract_present: true,
            },
            evidence_refs: [
              {
                id: 'input_attempt_yuk792_canary_20260731c_a',
                kind: 'event',
              },
              {
                id: 'input_attempt_yuk792_canary_20260731c_b',
                kind: 'event',
              },
            ],
            proposal_kind: 'conjecture',
            evidence_ref_semantics: 'supporting_references_noncausal',
          },
          created_at: '2026-07-31T01:33:04.175Z',
          subject_id: 'kc_yuk792_canary_20260731c',
          dispatch_seq: 34,
          subject_kind: 'mind_model',
          payload_present: true,
          correction_state: 'active',
          caused_by_event_id: null,
          correction_event_id: null,
          replacement_event_id: null,
          redacted_payload_groups: [
            'anti_guilt_metrics',
            'execution_metadata',
            'free_text',
            'future_diagnostics',
            'private_metadata',
            'review_prose',
          ],
          payload_projection_status: 'typed_safe',
        },
        requested_event_id: 'conjecture_yuk792_canary_20260731c',
      },
      attempt: null,
      question: null,
      timeline: [],
      claim_support: {
        causal_edges: 'caused_by_event_id_only',
        temporal_order: 'noncausal',
        activation_policy: 'not_observed',
        necessary_conditions: 'not_supported',
        sufficient_conditions: 'not_supported',
      },
      linked_records: [],
      timeline_scope: 'same_question_context_noncausal',
      timeline_coverage: {
        limit: 10,
        complete: null,
        has_more: null,
        returned_count: 0,
      },
      causal_neighborhood: {
        parent: null,
        coverage: {
          limit: 10,
          complete: true,
          has_more: false,
          returned_count: 2,
          total_direct_children: 2,
        },
        direct_children: [
          {
            action: 'experimental:probe_result',
            outcome: null,
            event_id: 'sg6aqgpq6l3wp5maslkvz12j',
            evidence: {
              kind: 'probe_result',
              outcome: 0,
              resolution: 'evidence_for',
              response_judgement: {
                gradable: true,
                reason_code: 'target_error_signature_matched',
                rule_version: 'conjecture_probe_response_signature_v1',
                answer_result: 'incorrect',
                target_error_match: 'matched',
              },
              conjecture_event_id: 'conjecture_yuk792_canary_20260731c',
              resolution_rule_version: 'within_learner_probe_recurrence_v2',
              independent_probe_question_ids: ['kbpvpcl6o9oep5s1e2oav5s0'],
            },
            created_at: '2026-07-31T02:45:58.045Z',
            subject_id: 'kbpvpcl6o9oep5s1e2oav5s0',
            dispatch_seq: 37,
            subject_kind: 'question',
            payload_present: true,
            correction_state: 'active',
            caused_by_event_id: 'conjecture_yuk792_canary_20260731c',
            correction_event_id: null,
            replacement_event_id: null,
            redacted_payload_groups: [
              'anti_guilt_metrics',
              'image_refs',
              'learner_answer',
              'review_prose',
            ],
            payload_projection_status: 'typed_safe',
          },
          {
            action: 'rate',
            outcome: 'success',
            event_id: 'weitr0eg3au983xxf4bpowkr',
            evidence: {
              kind: 'rate',
              rating: 'accept',
              conjecture_id: 'conjecture_yuk792_canary_20260731c',
              calibration_anchor: 'accept',
              corrected_by_owner: false,
              referenced_knowledge_ids: ['kc_yuk792_canary_20260731c'],
            },
            created_at: '2026-07-31T01:33:28.365Z',
            subject_id: 'conjecture_yuk792_canary_20260731c',
            dispatch_seq: 35,
            subject_kind: 'event',
            payload_present: true,
            correction_state: 'active',
            caused_by_event_id: 'conjecture_yuk792_canary_20260731c',
            correction_event_id: null,
            replacement_event_id: null,
            redacted_payload_groups: ['free_text', 'private_metadata'],
            payload_projection_status: 'typed_safe',
          },
        ],
        relation_semantics: 'direct_children_only',
      },
      question_availability: 'not_resolved',
    },
    error_reason: null,
    executed: true,
  },
  {
    name: 'get_attempt_context',
    effect: 'read',
    input: {
      causalLimit: 10,
      attemptEventId: 'q2lm07istehqzj8ar2slphpy',
    },
    output: {
      cause: null,
      lookup: {
        status: 'unsupported_event',
        observed: {
          action: 'experimental:probe_result',
          outcome: null,
          event_id: 'q2lm07istehqzj8ar2slphpy',
          evidence: {
            kind: 'probe_result',
            outcome: 0,
            resolution: 'evidence_for',
            response_judgement: {
              gradable: true,
              reason_code: 'target_error_signature_matched',
              rule_version: 'conjecture_probe_response_signature_v1',
              answer_result: 'incorrect',
              target_error_match: 'matched',
            },
            conjecture_event_id: 'conjecture_yuk792_canary_20260731b',
            resolution_rule_version: 'within_learner_probe_recurrence_v2',
            independent_probe_question_ids: ['v7glkid9penckj7zm4i5ub4q'],
          },
          created_at: '2026-07-31T01:02:19.777Z',
          subject_id: 'v7glkid9penckj7zm4i5ub4q',
          dispatch_seq: 30,
          subject_kind: 'question',
          payload_present: true,
          correction_state: 'active',
          caused_by_event_id: 'conjecture_yuk792_canary_20260731b',
          correction_event_id: null,
          replacement_event_id: null,
          redacted_payload_groups: [
            'anti_guilt_metrics',
            'image_refs',
            'learner_answer',
            'review_prose',
          ],
          payload_projection_status: 'typed_safe',
        },
        requested_event_id: 'q2lm07istehqzj8ar2slphpy',
      },
      attempt: null,
      question: null,
      timeline: [],
      claim_support: {
        causal_edges: 'caused_by_event_id_only',
        temporal_order: 'noncausal',
        activation_policy: 'not_observed',
        necessary_conditions: 'not_supported',
        sufficient_conditions: 'not_supported',
      },
      linked_records: [],
      timeline_scope: 'same_question_context_noncausal',
      timeline_coverage: {
        limit: 10,
        complete: null,
        has_more: null,
        returned_count: 0,
      },
      causal_neighborhood: {
        parent: {
          action: 'experimental:proposal',
          outcome: 'partial',
          event_id: 'conjecture_yuk792_canary_20260731b',
          evidence: {
            kind: 'proposal',
            target: {
              subject_id: 'kc_yuk792_canary_20260731b',
              subject_kind: 'mind_model',
            },
            conjecture: {
              knowledge_id: 'kc_yuk792_canary_20260731b',
              claim_present: true,
              probe_quality: {
                passed: true,
                attempt_count: 1,
                schema_version: 3,
              },
              cause_category: 'concept_misunderstanding',
              discriminating: true,
              corrected_by_owner: false,
              recurrence_gate_satisfied: true,
              diagnostic_contract_present: true,
              primary_probe_contract_present: true,
              followup_probe_contract_present: true,
            },
            evidence_refs: [
              {
                id: 'input_attempt_yuk792_canary_20260731b_a',
                kind: 'event',
              },
              {
                id: 'input_attempt_yuk792_canary_20260731b_b',
                kind: 'event',
              },
            ],
            proposal_kind: 'conjecture',
            evidence_ref_semantics: 'supporting_references_noncausal',
          },
          created_at: '2026-07-31T00:31:14.848Z',
          subject_id: 'kc_yuk792_canary_20260731b',
          dispatch_seq: 23,
          subject_kind: 'mind_model',
          payload_present: true,
          correction_state: 'active',
          caused_by_event_id: null,
          correction_event_id: null,
          replacement_event_id: null,
          redacted_payload_groups: [
            'anti_guilt_metrics',
            'execution_metadata',
            'free_text',
            'future_diagnostics',
            'private_metadata',
            'review_prose',
          ],
          payload_projection_status: 'typed_safe',
        },
        coverage: {
          limit: 10,
          complete: true,
          has_more: false,
          returned_count: 2,
          total_direct_children: 2,
        },
        direct_children: [
          {
            action: 'experimental:intervention_preparation_failed',
            outcome: 'failure',
            event_id: 'r7vz1nhfaswxtjqlc0oe0ub5',
            evidence: {
              kind: 'intervention_preparation_failed',
              failure_code: 'author_output_invalid',
              knowledge_id: 'kc_yuk792_canary_20260731b',
              intervention_id: 'int_22bc5072807d2a6b3ad091656073d062',
              conjecture_event_id: 'conjecture_yuk792_canary_20260731b',
              intervention_version: 1,
            },
            created_at: '2026-07-31T01:04:11.786Z',
            subject_id: 'q2lm07istehqzj8ar2slphpy',
            dispatch_seq: 31,
            subject_kind: 'event',
            payload_present: true,
            correction_state: 'active',
            caused_by_event_id: 'q2lm07istehqzj8ar2slphpy',
            correction_event_id: null,
            replacement_event_id: null,
            redacted_payload_groups: [],
            payload_projection_status: 'typed_safe',
          },
          {
            action: 'experimental:prediction_score',
            outcome: null,
            event_id: 'prediction_score:q2lm07istehqzj8ar2slphpy',
            evidence: {
              kind: 'prediction_score',
              outcome: 0,
              resolution: 'evidence_for',
              score_basis: 'single_point',
              knowledge_id: 'kc_yuk792_canary_20260731b',
              discriminating: true,
              probe_question_id: 'v7glkid9penckj7zm4i5ub4q',
              conjecture_event_id: 'conjecture_yuk792_canary_20260731b',
              probe_result_event_id: 'q2lm07istehqzj8ar2slphpy',
              independent_probe_question_ids: ['v7glkid9penckj7zm4i5ub4q'],
            },
            created_at: '2026-07-31T01:02:19.777Z',
            subject_id: 'q2lm07istehqzj8ar2slphpy',
            dispatch_seq: 46,
            subject_kind: 'event',
            payload_present: true,
            correction_state: 'active',
            caused_by_event_id: 'q2lm07istehqzj8ar2slphpy',
            correction_event_id: null,
            replacement_event_id: null,
            redacted_payload_groups: ['anti_guilt_metrics', 'execution_metadata'],
            payload_projection_status: 'typed_safe',
          },
        ],
        relation_semantics: 'direct_children_only',
      },
      question_availability: 'not_resolved',
    },
    error_reason: null,
    executed: true,
  },
  {
    name: 'get_attempt_context',
    effect: 'read',
    input: {
      causalLimit: 10,
      attemptEventId: 'sg6aqgpq6l3wp5maslkvz12j',
    },
    output: {
      cause: null,
      lookup: {
        status: 'unsupported_event',
        observed: {
          action: 'experimental:probe_result',
          outcome: null,
          event_id: 'sg6aqgpq6l3wp5maslkvz12j',
          evidence: {
            kind: 'probe_result',
            outcome: 0,
            resolution: 'evidence_for',
            response_judgement: {
              gradable: true,
              reason_code: 'target_error_signature_matched',
              rule_version: 'conjecture_probe_response_signature_v1',
              answer_result: 'incorrect',
              target_error_match: 'matched',
            },
            conjecture_event_id: 'conjecture_yuk792_canary_20260731c',
            resolution_rule_version: 'within_learner_probe_recurrence_v2',
            independent_probe_question_ids: ['kbpvpcl6o9oep5s1e2oav5s0'],
          },
          created_at: '2026-07-31T02:45:58.045Z',
          subject_id: 'kbpvpcl6o9oep5s1e2oav5s0',
          dispatch_seq: 37,
          subject_kind: 'question',
          payload_present: true,
          correction_state: 'active',
          caused_by_event_id: 'conjecture_yuk792_canary_20260731c',
          correction_event_id: null,
          replacement_event_id: null,
          redacted_payload_groups: [
            'anti_guilt_metrics',
            'image_refs',
            'learner_answer',
            'review_prose',
          ],
          payload_projection_status: 'typed_safe',
        },
        requested_event_id: 'sg6aqgpq6l3wp5maslkvz12j',
      },
      attempt: null,
      question: null,
      timeline: [],
      claim_support: {
        causal_edges: 'caused_by_event_id_only',
        temporal_order: 'noncausal',
        activation_policy: 'not_observed',
        necessary_conditions: 'not_supported',
        sufficient_conditions: 'not_supported',
      },
      linked_records: [],
      timeline_scope: 'same_question_context_noncausal',
      timeline_coverage: {
        limit: 10,
        complete: null,
        has_more: null,
        returned_count: 0,
      },
      causal_neighborhood: {
        parent: {
          action: 'experimental:proposal',
          outcome: 'partial',
          event_id: 'conjecture_yuk792_canary_20260731c',
          evidence: {
            kind: 'proposal',
            target: {
              subject_id: 'kc_yuk792_canary_20260731c',
              subject_kind: 'mind_model',
            },
            conjecture: {
              knowledge_id: 'kc_yuk792_canary_20260731c',
              claim_present: true,
              probe_quality: {
                passed: true,
                attempt_count: 1,
                schema_version: 3,
              },
              cause_category: 'concept_misunderstanding',
              discriminating: true,
              corrected_by_owner: false,
              recurrence_gate_satisfied: true,
              diagnostic_contract_present: true,
              primary_probe_contract_present: true,
              followup_probe_contract_present: true,
            },
            evidence_refs: [
              {
                id: 'input_attempt_yuk792_canary_20260731c_a',
                kind: 'event',
              },
              {
                id: 'input_attempt_yuk792_canary_20260731c_b',
                kind: 'event',
              },
            ],
            proposal_kind: 'conjecture',
            evidence_ref_semantics: 'supporting_references_noncausal',
          },
          created_at: '2026-07-31T01:33:04.175Z',
          subject_id: 'kc_yuk792_canary_20260731c',
          dispatch_seq: 34,
          subject_kind: 'mind_model',
          payload_present: true,
          correction_state: 'active',
          caused_by_event_id: null,
          correction_event_id: null,
          replacement_event_id: null,
          redacted_payload_groups: [
            'anti_guilt_metrics',
            'execution_metadata',
            'free_text',
            'future_diagnostics',
            'private_metadata',
            'review_prose',
          ],
          payload_projection_status: 'typed_safe',
        },
        coverage: {
          limit: 10,
          complete: true,
          has_more: false,
          returned_count: 2,
          total_direct_children: 2,
        },
        direct_children: [
          {
            action: 'experimental:intervention_activated',
            outcome: 'success',
            event_id: 'ee4x94n2wt1o8sh8z6zxn0yj',
            evidence: {
              kind: 'intervention_activated',
              method_id: 'refutation',
              diagnostics: [
                {
                  kind: 'immediate',
                  due_at: '2026-07-31T02:47:43.442Z',
                  question_id: 'intervention:int_d7c65598dd0a65788200c7294c20984c:v1:immediate',
                },
                {
                  kind: 'delayed',
                  due_at: '2026-08-07T02:47:43.442Z',
                  question_id: 'intervention:int_d7c65598dd0a65788200c7294c20984c:v1:delayed',
                },
                {
                  kind: 'transfer',
                  due_at: '2026-08-21T02:47:43.442Z',
                  question_id: 'intervention:int_d7c65598dd0a65788200c7294c20984c:v1:transfer',
                },
              ],
              knowledge_id: 'kc_yuk792_canary_20260731c',
              delivery_mode: 'eligible',
              intervention_id: 'int_d7c65598dd0a65788200c7294c20984c',
              package_version: 1,
              conjecture_event_id: 'conjecture_yuk792_canary_20260731c',
              intervention_version: 1,
            },
            created_at: '2026-07-31T02:47:43.442Z',
            subject_id: 'sg6aqgpq6l3wp5maslkvz12j',
            dispatch_seq: 38,
            subject_kind: 'event',
            payload_present: true,
            correction_state: 'active',
            caused_by_event_id: 'sg6aqgpq6l3wp5maslkvz12j',
            correction_event_id: null,
            replacement_event_id: null,
            redacted_payload_groups: ['future_diagnostics', 'private_metadata'],
            payload_projection_status: 'typed_safe',
          },
          {
            action: 'experimental:prediction_score',
            outcome: null,
            event_id: 'prediction_score:sg6aqgpq6l3wp5maslkvz12j',
            evidence: {
              kind: 'prediction_score',
              outcome: 0,
              resolution: 'evidence_for',
              score_basis: 'single_point',
              knowledge_id: 'kc_yuk792_canary_20260731c',
              discriminating: true,
              probe_question_id: 'kbpvpcl6o9oep5s1e2oav5s0',
              conjecture_event_id: 'conjecture_yuk792_canary_20260731c',
              probe_result_event_id: 'sg6aqgpq6l3wp5maslkvz12j',
              independent_probe_question_ids: ['kbpvpcl6o9oep5s1e2oav5s0'],
            },
            created_at: '2026-07-31T02:45:58.045Z',
            subject_id: 'sg6aqgpq6l3wp5maslkvz12j',
            dispatch_seq: 47,
            subject_kind: 'event',
            payload_present: true,
            correction_state: 'active',
            caused_by_event_id: 'sg6aqgpq6l3wp5maslkvz12j',
            correction_event_id: null,
            replacement_event_id: null,
            redacted_payload_groups: ['anti_guilt_metrics', 'execution_metadata'],
            payload_projection_status: 'typed_safe',
          },
        ],
        relation_semantics: 'direct_children_only',
      },
      question_availability: 'not_resolved',
    },
    error_reason: null,
    executed: true,
  },
  {
    name: 'query_events',
    effect: 'read',
    input: {
      filter: {
        limit: 20,
        action: 'attempt',
        sinceDays: 7,
      },
    },
    output: {
      total: 0,
      events: [],
      coverage: {
        limit: 20,
        order: 'created_at_desc_dispatch_seq_desc_id_desc',
        has_more: false,
        next_cursor: null,
        observed_at: '2026-08-02T00:08:12.247Z',
        window_start: '2026-07-26T00:08:12.247Z',
        returned_count: 0,
        complete_for_window: true,
        observed_dispatch_seq: 697,
        complete_for_window_scope: 'response_contains_full_filter_observation_window',
        remaining_window_after_cursor_complete: null,
      },
      subject_scope: {
        subject_id: null,
        subject_kind: null,
        required_followup: 'none',
        cross_stage_claim_status: 'not_subject_scoped',
        all_subject_kinds_included: null,
      },
      filter_applied: {
        limit: 20,
        action: 'attempt',
        eventId: null,
        outcome: null,
        actorRef: null,
        actorKind: null,
        sinceDays: 7,
        subjectId: null,
        subjectKind: null,
        causedByEventId: null,
        siblingOfEventId: null,
      },
      match_semantics: {
        action: 'exact',
        filters: 'and',
        sibling: 'same_non_null_parent_excludes_focal',
        event_id: 'exact',
        caused_by: 'direct_children_only',
        subject_id: 'exact',
        subject_kind: 'exact',
      },
      claim_boundaries: {
        zero_rows_scope: 'exact_filters_and_full_observation_window',
        supports_entity_inventory_claim: false,
        supports_lifecycle_status_count_claim: false,
      },
      relation_applied: {
        kind: 'none',
        status: 'not_requested',
      },
    },
    error_reason: null,
    executed: true,
  },
  {
    name: 'query_events',
    effect: 'read',
    input: {
      filter: {
        limit: 20,
        action: 'review',
        sinceDays: 7,
      },
    },
    output: {
      total: 1,
      events: [
        {
          id: 'si6y0w14iihyogdifj7w60c1',
          action: 'review',
          outcome: 'success',
          actor_ref: 'self',
          actor_kind: 'user',
          created_at: '2026-07-31T02:51:12.154Z',
          session_id: null,
          subject_id: 'intervention:int_d7c65598dd0a65788200c7294c20984c:v1:immediate',
          dispatch_seq: 39,
          subject_kind: 'question',
          correction_state: 'active',
          caused_by_event_id: null,
          correction_event_id: null,
          replacement_event_id: null,
        },
      ],
      coverage: {
        limit: 20,
        order: 'created_at_desc_dispatch_seq_desc_id_desc',
        has_more: false,
        next_cursor: null,
        observed_at: '2026-08-02T00:08:14.809Z',
        window_start: '2026-07-26T00:08:14.809Z',
        returned_count: 1,
        complete_for_window: true,
        observed_dispatch_seq: 698,
        complete_for_window_scope: 'response_contains_full_filter_observation_window',
        remaining_window_after_cursor_complete: null,
      },
      subject_scope: {
        subject_id: null,
        subject_kind: null,
        required_followup: 'none',
        cross_stage_claim_status: 'not_subject_scoped',
        all_subject_kinds_included: null,
      },
      filter_applied: {
        limit: 20,
        action: 'review',
        eventId: null,
        outcome: null,
        actorRef: null,
        actorKind: null,
        sinceDays: 7,
        subjectId: null,
        subjectKind: null,
        causedByEventId: null,
        siblingOfEventId: null,
      },
      match_semantics: {
        action: 'exact',
        filters: 'and',
        sibling: 'same_non_null_parent_excludes_focal',
        event_id: 'exact',
        caused_by: 'direct_children_only',
        subject_id: 'exact',
        subject_kind: 'exact',
      },
      claim_boundaries: {
        zero_rows_scope: 'exact_filters_and_full_observation_window',
        supports_entity_inventory_claim: false,
        supports_lifecycle_status_count_claim: false,
      },
      relation_applied: {
        kind: 'none',
        status: 'not_requested',
      },
    },
    error_reason: null,
    executed: true,
  },
  {
    name: 'get_review_due',
    effect: 'read',
    input: {
      limit: 50,
      includeReason: true,
    },
    output: {
      rows: [],
      as_of: '2026-08-02T00:08:11.669Z',
      queue_scope: 'due_now_and_never_reviewed_failures',
      queue_summary: {
        count_scope: 'returned_actionable_rows_only',
        overdue_count: 0,
        total_returned: 0,
        top_knowledge_ids: [],
        never_reviewed_count: 0,
      },
      queue_coverage: {
        limit: 50,
        has_more: null,
        claim_scope: 'returned_actionable_rows_only',
        completeness: 'unknown',
        returned_count: 0,
        total_matching_count: null,
        complete_for_due_now_window: null,
        supports_exhaustive_zero_claim: false,
      },
      queue_assertion: {
        cleared: null,
        failed_entity_count: null,
        queued_entity_count: null,
        in_progress_entity_count: null,
        actionable_due_total_count: null,
        actionable_due_returned_count: 0,
      },
      future_projections: [
        {
          state: {
            due: '2026-08-07T02:51:12.154Z',
            reps: 0,
            state: 'new',
            lapses: 0,
            stability: 0,
            difficulty: 0,
            last_review: null,
            elapsed_days: 0,
            learning_steps: 0,
            scheduled_days: 0,
          },
          due_at: '2026-08-07T02:51:12.154Z',
          timing: 'future',
          subject_id: 'intervention:int_d7c65598dd0a65788200c7294c20984c:v1:delayed',
          subject_kind: 'question',
          last_review_event_id: null,
        },
        {
          state: {
            due: '2026-08-21T02:51:12.154Z',
            reps: 0,
            state: 'new',
            lapses: 0,
            stability: 0,
            difficulty: 0,
            last_review: null,
            elapsed_days: 0,
            learning_steps: 0,
            scheduled_days: 0,
          },
          due_at: '2026-08-21T02:51:12.154Z',
          timing: 'future',
          subject_id: 'intervention:int_d7c65598dd0a65788200c7294c20984c:v1:transfer',
          subject_kind: 'question',
          last_review_event_id: null,
        },
      ],
      entity_status_coverage: {
        intervention: 'not_observed',
        learning_item: 'not_observed',
      },
      fsrs_projection_summary: {
        subject_scope: 'material_fsrs_state_rows',
        total_state_count: 2,
        future_state_count: 2,
        due_now_state_count: 0,
        earliest_future_due_at: '2026-08-07T02:51:12.154Z',
        supports_actionable_queue_claim: false,
      },
      future_projection_coverage: {
        limit: 50,
        complete: true,
        has_more: false,
        completeness: 'complete',
        returned_count: 2,
        total_future_count: 2,
      },
    },
    error_reason: null,
    executed: true,
  },
] as const satisfies readonly ToolExecutionResultObservation[];
