// ADR-0031 / YUK-304 (quiz C→A, lane B) — the author_question knowledge|material
// seed core.
//
// One call = ONE original draft question, generated by the single-shot
// QuestionAuthorTask (决定6: NOT the QuizGenTask agent loop — no Tavily, no
// 8-iteration budget; the COPILOT is the orchestrator and calls author_question
// once per question it wants).
//
// Write policy (决定4 + 决定5): the question row is INSERTed immediately with
// draft_status='draft' — non-destructive by the Option-B gate semantics
// (invisible to pool / review / FSRS, quiz_gen precedent) — and a
// `question_draft` proposal is written IN THE SAME TRANSACTION. Accept
// (acceptQuestionDraftProposal, src/server/proposals/actions.ts) promotes
// draft→active + FSRS-enrolls. Draft-row-at-propose-time (not insert-on-accept)
// is load-bearing for the same-turn 组卷 flow: write_quiz (RP-2 draft-allowed)
// must reference a REAL question_id in the same copilot turn.
//
// NO cooldown / dedup here — authoring several questions on one knowledge node
// within one turn is the INTENDED flow (the copilot assembles a multi-question
// paper by calling this repeatedly), in deliberate contrast to
// record_promotion's pendingProposalWithCooldown.

import { createId } from '@paralleldrive/cuid2';
import { and, inArray, isNull } from 'drizzle-orm';

import {
  QuestionAuthorDraft,
  type QuestionAuthorDraftT,
  normalizeAuthorStructured,
} from '@/core/schema/question_author';
import type { Db } from '@/db/client';
import { knowledge, question } from '@/db/schema';
import { type TaskTextRunFn, aiAgentRef } from '@/server/ai/provenance';
import { getEffectiveDomain } from '@/capabilities/knowledge/server/domain';
import { writeAiProposal } from '@/server/proposals/writer';
import { resolveSubjectProfile } from '@/subjects/profile';
import { normalizeToCanonicalKind } from '@/subjects/question-kind';

const PROMPT_PREVIEW_CHARS = 120;

export interface QuestionAuthorSeed {
  seed_mode: 'knowledge' | 'material';
  knowledge_ids: string[];
  requested_kind?: string;
  difficulty?: number;
  /** REQUIRED for seed_mode='material' (the task has no fetch tool — critic #5). */
  material_body_md?: string;
  /** Provenance-only metadata; never fetched (single-shot task, no Tavily). */
  material_url?: string;
  material_title?: string;
}

export interface QuestionAuthorDeps {
  db: Db;
  /** actor_ref for the written proposal (ctx.callerActor.ref). */
  actorRef: string;
  taskRunId: string;
  causedByEventId?: string;
  runTaskFn: TaskTextRunFn;
}

export type RunQuestionAuthorResult =
  | { status: 'proposed'; proposalId: string; questionId: string }
  | { status: 'skipped:knowledge_not_found' };

// brace-slice + Zod parse for the raw text output (照 quiz_gen parseOutput).
// Throws on no-JSON / JSON.parse failure / schema mismatch — the tool wrapper
// (authorQuestionExecute) converts the throw to status:'failed'.
export function parseQuestionAuthorOutput(text: string): QuestionAuthorDraftT {
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start === -1 || end === -1 || end < start) {
    throw new Error('parseQuestionAuthorOutput: no JSON object found in text');
  }
  let json: unknown;
  try {
    json = JSON.parse(text.slice(start, end + 1));
  } catch (e) {
    throw new Error(`parseQuestionAuthorOutput: JSON.parse failed: ${(e as Error).message}`);
  }
  const parsed = QuestionAuthorDraft.safeParse(json);
  if (!parsed.success) {
    throw new Error(
      `parseQuestionAuthorOutput: schema invalid: ${parsed.error.issues.map((i) => i.message).join('; ')}`,
    );
  }
  return parsed.data;
}

/**
 * Generate ONE draft question seeded by knowledge nodes and/or pasted material,
 * INSERT it as draft_status='draft', and write the paired `question_draft`
 * proposal in the same transaction.
 *
 * Soft-skips (returns a status) only on a fully-invalid knowledge seed; every
 * other failure (LLM outage / parse failure / malformed tree) THROWS — the
 * DomainTool wrapper maps throws to status:'failed'.
 */
export async function runQuestionAuthor(
  seed: QuestionAuthorSeed,
  deps: QuestionAuthorDeps,
): Promise<RunQuestionAuthorResult> {
  const { db } = deps;

  // material seed requires the body — the single-shot task has no fetch tool, so
  // a URL-only seed would hallucinate the passage (critic #5). The DomainTool
  // boundary (validateAuthorQuestionInput) enforces this too; this guard covers
  // direct callers.
  if (seed.seed_mode === 'material' && !seed.material_body_md?.trim()) {
    throw new Error("question_author seed_mode 'material' requires material_body_md");
  }

  // Validate the seed knowledge ids against live (non-archived) nodes. All
  // invalid → soft-skip; partial → intersect (salvage, quiz_gen policy).
  const wanted = [...new Set(seed.knowledge_ids)];
  const nodes = wanted.length
    ? await db
        .select({ id: knowledge.id, name: knowledge.name })
        .from(knowledge)
        .where(and(inArray(knowledge.id, wanted), isNull(knowledge.archived_at)))
    : [];
  if (nodes.length === 0) {
    return { status: 'skipped:knowledge_not_found' };
  }
  const validIds = nodes.map((n) => n.id);
  const validIdSet = new Set(validIds);

  // Subject profile via the first valid node's EFFECTIVE domain (科目是视角:
  // child nodes usually carry domain=null and inherit from an ancestor, so the
  // raw column would mis-resolve to the default profile; getEffectiveDomain is
  // the derivation owner). "First" follows the SEED's original order — `nodes`
  // row order is DB-arbitrary (no ORDER BY), which would make the prompt voice
  // nondeterministic for mixed-subject seeds (review LOW). The profile only
  // shapes the prompt VOICE, so a degenerate tree (root with null domain —
  // invariant violation in legacy / fixture data) degrades to the default
  // profile instead of failing the run.
  const firstValidId = wanted.find((id) => validIdSet.has(id)) ?? validIds[0];
  let effectiveDomain: string | null = null;
  try {
    effectiveDomain = await getEffectiveDomain(db, firstValidId);
  } catch {
    effectiveDomain = null;
  }
  const subjectProfile = resolveSubjectProfile(effectiveDomain);

  // Normalize requested_kind through the single-authority kind vocabulary
  // (image_candidate accept precedent): an unrecognized hint degrades to "no
  // pin" instead of confusing the prompt with an unknown word.
  const requestedKind = seed.requested_kind
    ? (normalizeToCanonicalKind(seed.requested_kind) ?? undefined)
    : undefined;

  const input = {
    seed_mode: seed.seed_mode,
    knowledge_context: nodes.map((n) => ({ id: n.id, name: n.name })),
    ...(requestedKind ? { requested_kind: requestedKind } : {}),
    ...(seed.difficulty !== undefined ? { requested_difficulty: seed.difficulty } : {}),
    ...(seed.material_body_md
      ? {
          material: {
            body_md: seed.material_body_md,
            ...(seed.material_title ? { title: seed.material_title } : {}),
          },
        }
      : {}),
  };

  const result = await deps.runTaskFn('QuestionAuthorTask', input, {
    db,
    subjectProfile,
  });
  const draft = parseQuestionAuthorOutput(result.text);

  // Hallucinated-id discipline: intersect the echoed knowledge_ids with the
  // validated seed set; an empty intersection falls back to the full validated
  // seed (the question was generated FOR those nodes — quiz_gen salvage policy).
  const echoed = draft.knowledge_ids.filter((id) => validIdSet.has(id));
  const questionKnowledgeIds = echoed.length > 0 ? echoed : validIds;

  // Server-side tree hardening: regenerate node ids, reject malformed shapes,
  // derive (and require non-empty) prompt_md / reference_md.
  const normalized = normalizeAuthorStructured(draft.structured);

  const now = new Date();
  const questionId = createId();
  const promptPreview =
    normalized.prompt_md.length > PROMPT_PREVIEW_CHARS
      ? `${normalized.prompt_md.slice(0, PROMPT_PREVIEW_CHARS)}…`
      : normalized.prompt_md;

  let proposalId = '';
  await db.transaction(async (tx) => {
    await tx.insert(question).values({
      id: questionId,
      kind: draft.kind,
      prompt_md: normalized.prompt_md,
      reference_md: normalized.reference_md,
      structured: normalized.structured,
      choices_md: draft.choices_md ?? null,
      rubric_json: draft.rubric_json ?? null,
      judge_kind_override: draft.judge_kind_override ?? null,
      knowledge_ids: questionKnowledgeIds,
      difficulty: draft.difficulty,
      // Zero-DDL QuestionSource enum value (business.ts) — question.source is text.
      source: 'copilot_authored',
      source_ref: null,
      // Option-B gate (quiz_gen precedent): invisible to pool / review / FSRS
      // until the question_draft proposal is accepted.
      draft_status: 'draft',
      created_by: aiAgentRef('QuestionAuthorTask', result),
      metadata: {
        author_question: {
          seed_mode: seed.seed_mode,
          ...(seed.material_url ? { material_url: seed.material_url } : {}),
          ...(seed.material_title ? { material_title: seed.material_title } : {}),
        },
      },
      created_at: now,
      updated_at: now,
    });

    proposalId = await writeAiProposal(tx, {
      actor_ref: deps.actorRef,
      payload: {
        kind: 'question_draft',
        target: { subject_kind: 'question', subject_id: questionId },
        reason_md: `copilot 拟题（seed=${seed.seed_mode}）：${promptPreview}`,
        evidence_refs: questionKnowledgeIds.map((id) => ({ kind: 'knowledge' as const, id })),
        proposed_change: {
          question_id: questionId,
          kind: draft.kind,
          difficulty: draft.difficulty,
          knowledge_ids: questionKnowledgeIds,
          seed_mode: seed.seed_mode,
          prompt_preview: promptPreview,
          ...(seed.material_url ? { material_url: seed.material_url } : {}),
        },
        rollback_plan: {
          action: 'dismiss proposal; the draft question stays inert (never pooled)',
        },
      },
      task_run_id: deps.taskRunId,
      caused_by_event_id: deps.causedByEventId ?? null,
      cost_usd: result.cost_usd,
    });
  });

  return { status: 'proposed', proposalId, questionId };
}
