/* Loom v2 — SEED data shaped as ADR-0006 v2 events.
   3 tables (in spirit): material, learning_session, event.
   This is just enough to make all 6 routes feel like a live system.

   Conventions:
   - event ids are e_NN, monotonic-ish
   - caused_by_event_id chains DAG
   - timestamps in unix seconds, anchored to NOW
*/

const NOW = Math.floor(Date.now() / 1000);
const MIN = 60, HR = 3600, DAY = 86400;

// ── material · knowledge ───────────────────────────────────
const KNOWLEDGE = [
  // §2.1 Phase 1 单 subject ——不引入跨学科 root。
  { id: 'k_wenyan',     name: '文言文',        parent_id: null,         depth: 0 },
  { id: 'k_xuci',       name: '文言虚词',      parent_id: 'k_wenyan',   depth: 1 },
  { id: 'k_xuci_zhi',   name: '之 (用法)',     parent_id: 'k_xuci',     depth: 2 },
  { id: 'k_xuci_zhi_attr', name: '之·定语标志', parent_id: 'k_xuci_zhi', depth: 3, proposed: true },
  { id: 'k_xuci_yu',    name: '于 (用法)',     parent_id: 'k_xuci',     depth: 2 },
  { id: 'k_xuci_er',    name: '而 (用法)',     parent_id: 'k_xuci',     depth: 2 },
  { id: 'k_shici',      name: '实词词义',      parent_id: 'k_wenyan',   depth: 1 },
  { id: 'k_juedu',      name: '断句',          parent_id: 'k_wenyan',   depth: 1 },
  { id: 'k_fanyi',      name: '翻译',          parent_id: 'k_wenyan',   depth: 1 },
];

// ── material · question ────────────────────────────────────
const QUESTIONS = {
  q1: {
    id: 'q1',
    prompt_md: '"之"在「古之学者必有师」中的用法是？',
    reference_md: '结构助词，定语标志，相当于「的」。',
    knowledge_ids: ['k_xuci_zhi'],
    source: { doc: '《师说》', page: 'p.1' },
  },
  q2: {
    id: 'q2',
    prompt_md: '翻译：「师者，所以传道受业解惑也」。',
    reference_md: '老师，是用来传授道理、教授学业、解答疑惑的人。',
    knowledge_ids: ['k_juedu', 'k_shici', 'k_fanyi'],
    source: { doc: '《师说》', page: 'p.1' },
  },
  q3: {
    id: 'q3',
    prompt_md: '「青，取之于蓝，而青于蓝」中两个"于"的用法？',
    reference_md: '前一个表来源(从)；后一个表比较(比)。',
    knowledge_ids: ['k_xuci_yu'],
    source: { doc: '《劝学》', page: 'p.3' },
  },
  q4: {
    id: 'q4',
    prompt_md: '「逝者如斯夫」中的"夫"应理解为？',
    reference_md: '语气助词，表感叹，相当于「啊」。',
    knowledge_ids: ['k_xuci'],
    source: { doc: '《论语·子罕》', page: '九年级 上' },
  },
  // variant generated by AI from q1
  q1v1: {
    id: 'q1v1',
    prompt_md: '辨析下列三句中"之"的用法：① 古之学者　② 蚓无爪牙之利　③ 句读之不知',
    reference_md: '① 助词，定语标志（的）　② 助词，定语后置标志　③ 助词，宾语前置标志',
    knowledge_ids: ['k_xuci_zhi'],
    source: { doc: 'AI 变式', page: '由 q1 派生' },
    derived_from: 'q1',
  },
};

// ── material · artifact ────────────────────────────────────
// AI-generated content lives here. Created by `action='generate'`.
const ARTIFACTS = {
  a_v_q1_1: {
    id: 'a_v_q1_1', kind: 'variant',
    title: '变式 1 · 三句辨析「之」',
    body_md: '辨析下列三句中"之"的用法：① 古之学者　② 蚓无爪牙之利　③ 句读之不知',
    question_id: 'q1v1',
  },
  a_n_zhi: {
    id: 'a_n_zhi', kind: 'note',
    title: '之 · 用法小结',
    body_md: '助词"之"的四种用法：① 定语标志（的）② 宾语前置标志 ③ 定语后置标志 ④ 用在主谓之间取消句子独立性。代词"之"指代前文出现的人/事/物。',
  },
  a_v_q3_1: {
    id: 'a_v_q3_1', kind: 'variant',
    title: '变式 1 · 三个"于"',
    body_md: '解释「夫人之相与，俯仰一世」「青取之于蓝」「冰，水为之而寒于水」中三个不同的"于"。',
  },
  a_q_xuci_zhi: {
    id: 'a_q_xuci_zhi', kind: 'quiz',
    title: '小测 · 之 vs 其',
    body_md: '5 题选择，对比"之"作助词与"其"作代词的语境。',
  },
};

// ── material · knowledge_edge (ADR-0010 mesh) ──────────────
// "Tree is the backbone; mesh is the muscle." mesh 只存非 tree 关系
// （brief v2.1 §2.1）—— parent_id 已经表达父子，不再镜像写一条 derived_from。
// 5 core relation_type + experimental:* escape.
const RELATION_TYPES = {
  prerequisite:    { label: '前置',       arrow: '→',  directed: true,  tone: 'coral'   },
  related_to:      { label: '相关',       arrow: '↔',  directed: false, tone: 'neutral' },
  contrasts_with:  { label: '对照',       arrow: '⇆',  directed: false, tone: 'hard'    },
  applied_in:      { label: '应用于',     arrow: '→',  directed: true,  tone: 'info'    },
  derived_from:    { label: '派生自',     arrow: '↳',  directed: true,  tone: 'good'    },
};

const KNOWLEDGE_EDGES = [
  {
    id: 'kedge_01',
    from_id: 'k_shici',       // 实词 (tree: 语文 > 文言文 > 实词词义)
    to_id:   'k_fanyi',       // 翻译 (同父 k_wenyan 下兄弟，跨子主题)
    relation_type: 'prerequisite', weight: 0.9,
    created_by: { actor_kind: 'agent', actor_ref: 'review' },
    reasoning: '近 30 天翻译错答 78% 涉及实词词义不准。',
    created_at: NOW - 3 * DAY,
  },
  {
    id: 'kedge_02',
    from_id: 'k_xuci_zhi',    // 之
    to_id:   'k_xuci_yu',     // 于 (同父兄弟，但需横向对照)
    relation_type: 'contrasts_with', weight: 0.7,
    created_by: { actor_kind: 'user' },
    created_at: NOW - 12 * DAY,
  },
  {
    id: 'kedge_03',
    from_id: 'k_shici',
    to_id:   'k_juedu',       // 断句
    relation_type: 'applied_in', weight: 0.6,
    created_by: { actor_kind: 'agent', actor_ref: 'review' },
    reasoning: '词义不准导致断句错位的 case study。',
    created_at: NOW - 2 * DAY,
  },
  {
    id: 'kedge_04',
    from_id: 'k_xuci_zhi',    // 之-用法
    to_id:   'k_juedu',       // 断句  — 同为文言文下但跨 2 个一级子树
    relation_type: 'related_to', weight: 0.4,
    created_by: { actor_kind: 'user' },
    reasoning: '断句时虚词位置是关键线索。',
    created_at: NOW - 8 * DAY,
  },
  {
    id: 'kedge_05',
    from_id: 'k_xuci_zhi',
    to_id:   'k_xuci_er',     // 同父兄弟弱关联
    relation_type: 'related_to', weight: 0.5,
    created_by: { actor_kind: 'user' },
    created_at: NOW - 18 * DAY,
  },
  {
    id: 'kedge_06',
    from_id: 'k_juedu',
    to_id:   'k_fanyi',       // 跨兄弟节点的前置依赖
    relation_type: 'prerequisite', weight: 0.8,
    created_by: { actor_kind: 'user' },
    created_at: NOW - 22 * DAY,
  },
];

// ── AI tools (brief v2.1 §1.6) ─────────────────────────────
// Tool catalog Copilot 能调的。每个 tool 调用以 event(action=
// 'experimental:tool_use') 落地，subject_kind='query'。
//
// §1.6 #3a: 每个 tool 自带 foldedSummary —— folded 状态下不用 generic
// 截断而是 tool 知道哪 1-2 个 args / result 该露出来。
const TOOLS = {
  query_events: {
    name: 'query_events',
    desc: '按 action / subject_kind / time 过滤 events 流',
    arg_label: 'filter',
    foldedSummary: (args, res) => {
      const f = args?.filter || '';
      const m = f.match(/action='?(\w+)'?/);
      const action = m ? m[1] : 'events';
      const window = args?.window?.match(/now\(\) - (\w+)/)?.[1] || '';
      return `${action}${window ? ' · ' + window : ''} · ${res?.result_summary || ''}`;
    },
  },
  query_knowledge: {
    name: 'query_knowledge',
    desc: '查 knowledge 节点 + mesh edges',
    arg_label: 'where',
    foldedSummary: (args, res) => {
      const id = args?.knowledge_id || args?.id;
      return `${id || 'k'} · ${res?.result_summary || ''}`;
    },
  },
  query_mistakes: {
    name: 'query_mistakes',
    desc: 'attempt:failure 视图带 judge_status / age / knowledge 联表',
    arg_label: 'filter',
    foldedSummary: (args, res) => {
      const k = args?.knowledge_id ? `k='${args.knowledge_id}'` : null;
      const f = args?.filter || '';
      const judge = /judge_status IS NULL/.test(f) ? '无 judge' : null;
      const out = /outcome='failure'/.test(f) ? 'failure' : null;
      const win = args?.window?.match(/now\(\) - (\w+)/)?.[1];
      const parts = [out, judge, win, k].filter(Boolean);
      return `${parts.join(' + ')} · ${res?.result_summary || ''}`;
    },
  },
  propose_variant: {
    name: 'propose_variant',
    desc: '从一道题生成 N 道同知识点变式',
    arg_label: 'from',
    foldedSummary: (args, res) => {
      const q = args?.question_id || 'q?';
      const n = args?.n || '?';
      return `${q} · n=${n} · ${res?.result_summary || ''}`;
    },
  },
  attribute_mistake: {
    name: 'attribute_mistake',
    desc: '给一个 attempt event 写 judge cause',
    arg_label: 'event_id',
    foldedSummary: (args, res) => {
      const e = args?.event_id || 'e?';
      return `${e} · ${res?.result_summary || ''}`;
    },
  },
  propose_edge: {
    name: 'propose_edge',
    desc: '提议一条 knowledge_edge（mesh）',
    arg_label: 'edge',
    foldedSummary: (args, res) => {
      const f = args?.from_id, t = args?.to_id, r = args?.relation_type;
      return `${f}→${t} ${r || ''} · ${res?.result_summary || ''}`;
    },
  },
};

// ── learning_session ──────────────────────────────────────
const SESSIONS = {
  s_ingest_now: {
    id: 's_ingest_now', type: 'ingestion', status: 'extracting',
    started_at: NOW - 12 * MIN, title: '语文练习册 p.45-46',
  },
  s_review_now: {
    id: 's_review_now', type: 'review', status: 'active',
    started_at: NOW - 4 * MIN,
  },
  s_dream_last_night: {
    id: 's_dream_last_night', type: 'ingestion', status: 'completed',
    started_at: NOW - 7 * HR, ended_at: NOW - 5 * HR, title: 'Dreaming 夜间扫描',
  },
  s_copilot: {
    id: 's_copilot', type: 'conversation', status: 'active',
    started_at: NOW - 2 * MIN, title: 'Copilot · 关于 q1',
  },
};

// ── event · the spine ─────────────────────────────────────
const EVENTS = [
  // ── Scenario 1: user wrong-answered q1 yesterday, AI ran the chain ──
  {
    id: 'e_01', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'attempt',
    subject_kind: 'question', subject_id: 'q1', outcome: 'failure',
    payload: { answer_md: '代词，指代「学者」。', duration_ms: 28400 },
    caused_by_event_id: null,
    created_at: NOW - DAY,
  },
  {
    id: 'e_02', session_id: null,
    actor_kind: 'agent', actor_ref: 'attribution', action: 'judge',
    subject_kind: 'event', subject_id: 'e_01', outcome: 'success',
    payload: {
      cause: {
        primary: 'concept', confidence: 0.87,
        ai_analysis_md: '把结构助词「之」误识为代词。下意识把"古之学者"翻译成 "学者古" → 倒推认为「之」指代「学者」。实际上「之」在此为定语标志（的）。',
        referenced_knowledge_ids: ['k_xuci_zhi'],
        actor_kind: 'agent',
      },
    },
    caused_by_event_id: 'e_01',
    task_run_id: 't_001', cost_micro_usd: 4200,
    created_at: NOW - DAY + 14,
  },
  {
    id: 'e_03', session_id: null,
    actor_kind: 'agent', actor_ref: 'variant_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_v_q1_1', outcome: 'success',
    payload: {
      artifact_kind: 'variant',
      title: '变式 1 · 三句辨析「之」',
      body_md: '辨析下列三句中"之"的用法：① 古之学者　② 蚓无爪牙之利　③ 句读之不知',
      referenced_event_ids: ['e_01'],
    },
    caused_by_event_id: 'e_02',
    task_run_id: 't_002', cost_micro_usd: 18600,
    created_at: NOW - DAY + 32,
  },
  {
    id: 'e_04', session_id: null,
    actor_kind: 'agent', actor_ref: 'propose', action: 'propose',
    subject_kind: 'knowledge', subject_id: 'k_xuci_zhi_attr', outcome: 'success',
    payload: {
      name: '之 · 定语标志',
      parent_id: 'k_xuci_zhi',
      reasoning: '错答 e_01 的归因结论 = 没区分助词与代词。建议为「之 (用法)」加一个细分子节点，专门聚焦"定语标志"这一最易混淆的子用法。',
    },
    caused_by_event_id: 'e_02',
    task_run_id: 't_003', cost_micro_usd: 12000,
    created_at: NOW - DAY + 48,
  },
  {
    id: 'e_05', session_id: null,
    actor_kind: 'agent', actor_ref: 'note_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_n_zhi', outcome: 'success',
    payload: {
      artifact_kind: 'note',
      title: '之 · 用法小结',
      body_md: ARTIFACTS.a_n_zhi.body_md,
    },
    caused_by_event_id: 'e_02',
    task_run_id: 't_004', cost_micro_usd: 9800,
    created_at: NOW - DAY + 70,
  },

  // ── Scenario 2: q2 wrong-answer 2 days ago, AI judged ──
  {
    id: 'e_10', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'attempt',
    subject_kind: 'question', subject_id: 'q2', outcome: 'failure',
    payload: { answer_md: '老师所以传授道理、学业和解答疑惑。', duration_ms: 52000 },
    caused_by_event_id: null,
    created_at: NOW - 2 * DAY,
  },
  {
    id: 'e_11', session_id: null,
    actor_kind: 'agent', actor_ref: 'attribution', action: 'judge',
    subject_kind: 'event', subject_id: 'e_10', outcome: 'success',
    payload: {
      cause: {
        primary: 'expression', confidence: 0.74,
        ai_analysis_md: '理解正确但表述卡在"所以"的现代汉语化。「所以」在此=「用来…的（人）」，是名词性结构，不能直接套现代"所以"。',
        referenced_knowledge_ids: ['k_shici', 'k_fanyi'],
        actor_kind: 'agent',
      },
    },
    caused_by_event_id: 'e_10',
    task_run_id: 't_010', cost_micro_usd: 4400,
    created_at: NOW - 2 * DAY + 18,
  },

  // ── Scenario 3: q3 wrong-answered 1 hour ago — judge is in-flight ──
  {
    id: 'e_20', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'attempt',
    subject_kind: 'question', subject_id: 'q3', outcome: 'failure',
    payload: { answer_md: '都表示比较。', duration_ms: 19200 },
    caused_by_event_id: null,
    created_at: NOW - 12 * MIN,
  },
  // judge pending (no e_21 yet)

  // ── Scenario 4: nightly Dreaming agent (cron) — last night ──
  {
    id: 'e_30', session_id: 's_dream_last_night',
    actor_kind: 'cron', actor_ref: 'nightly_dreaming', action: 'experimental:trigger_dreaming_scan',
    subject_kind: 'event', subject_id: 's_dream_last_night', outcome: null,
    payload: {}, caused_by_event_id: null,
    created_at: NOW - 7 * HR,
  },
  {
    id: 'e_31', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'dreaming', action: 'experimental:scan',
    subject_kind: 'knowledge', subject_id: 'k_xuci_zhi', outcome: 'success',
    payload: { notes: '最近 5 次错答有 3 次落在「之」上' },
    caused_by_event_id: 'e_30',
    task_run_id: 't_030', cost_micro_usd: 8200,
    created_at: NOW - 7 * HR + 3 * MIN,
  },
  // §1.6 #6 — tool-use trace inside the Dreaming chain
  // The agent that "scanned" k_xuci_zhi then asked the data layer for
  // similar mistakes before deciding to generate variants. Visible in
  // /inbox EventChain so user can see *how* AI arrived at the proposal.
  {
    id: 'e_31a', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'dreaming', action: 'experimental:tool_use',
    subject_kind: 'query', subject_id: 'tu_dr_001', outcome: 'success',
    payload: {
      tool: 'query_mistakes',
      args: { knowledge_id: 'k_xuci_zhi', filter: "outcome='failure'", window: 'now() - 30d' },
      result_summary: '5 found · 3 distinct causes',
      result_data: [
        { event_id: 'e_01', cause: 'concept', age: '1 天前' },
        { event_id: 'e_attp_a', cause: 'concept', age: '3 天前' },
        { event_id: 'e_attp_b', cause: 'method',  age: '5 天前' },
        { event_id: 'e_attp_c', cause: 'concept', age: '9 天前' },
        { event_id: 'e_attp_d', cause: 'reading', age: '14 天前' },
      ],
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_030a', cost_micro_usd: 1200,
    created_at: NOW - 7 * HR + 4 * MIN,
  },
  {
    id: 'e_32', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'variant_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_v_q3_1', outcome: 'success',
    payload: {
      artifact_kind: 'variant',
      title: '变式 1 · 三个"于"',
      body_md: ARTIFACTS.a_v_q3_1.body_md,
    },
    caused_by_event_id: 'e_31a',
    task_run_id: 't_031', cost_micro_usd: 16800,
    created_at: NOW - 7 * HR + 6 * MIN,
  },
  {
    id: 'e_33', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'note_gen', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_q_xuci_zhi', outcome: 'success',
    payload: {
      artifact_kind: 'quiz',
      title: '小测 · 之 vs 其',
      body_md: ARTIFACTS.a_q_xuci_zhi.body_md,
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_032', cost_micro_usd: 11400,
    created_at: NOW - 7 * HR + 9 * MIN,
  },
  {
    id: 'e_34', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'dreaming', action: 'propose',
    subject_kind: 'knowledge', subject_id: 'k_xuci_er', outcome: 'success',
    payload: {
      name: '而 · 转折 vs 并列',
      parent_id: 'k_xuci_er',
      reasoning: '当前 k_xuci_er 节点尚未拆分子用法，但用户最近 3 次"而"题目均答错于"转折/并列"识别。',
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_033', cost_micro_usd: 7200,
    created_at: NOW - 7 * HR + 11 * MIN,
  },
  {
    id: 'e_35', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'critique', action: 'experimental:critique',
    subject_kind: 'event', subject_id: 'e_32', outcome: 'failure',
    payload: { reason: '变式与原题"于"的难度梯度太陡，建议先出一个 2 选 1 的判断题再上升级。' },
    caused_by_event_id: 'e_32',
    task_run_id: 't_034', cost_micro_usd: 5600,
    created_at: NOW - 7 * HR + 14 * MIN,
  },

  // ── Mesh edge proposals (ADR-0010) — by Dreaming + Maintenance agents ──
  {
    id: 'e_36', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'maintenance', action: 'propose',
    subject_kind: 'knowledge_edge', subject_id: 'kedge_pending_01', outcome: 'success',
    payload: {
      from_id: 'k_shici', to_id: 'k_juedu',
      relation_type: 'prerequisite', weight: 0.85,
      reasoning: '近 30 天断句错答里 64% 同时被归因为实词词义不准。这条边目前是 applied_in（kedge_04），更准确是 prerequisite。',
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_036', cost_micro_usd: 9400,
    created_at: NOW - 7 * HR + 18 * MIN,
  },
  // (was e_37: derived_from k_xuci_zhi_attr → k_xuci_zhi —
  //  removed per brief v2.1 §2.1 — that's a tree parent relation,
  //  not a mesh edge. parent_id 已经表达。)
  {
    id: 'e_37', session_id: 's_dream_last_night',
    actor_kind: 'agent', actor_ref: 'maintenance', action: 'propose',
    subject_kind: 'knowledge_edge', subject_id: 'kedge_pending_02', outcome: 'success',
    payload: {
      from_id: 'k_xuci_er', to_id: 'k_xuci_yu',
      relation_type: 'contrasts_with', weight: 0.65,
      reasoning: '「而」与「于」都是虚词，但语法职能区分明显。近 14 天错答里 6 道同时涉及两个虚词的辨别。',
    },
    caused_by_event_id: 'e_31',
    task_run_id: 't_037', cost_micro_usd: 7200,
    created_at: NOW - 7 * HR + 22 * MIN,
  },

  // ── Reviews (FSRS) ────────────────────────────────────────
  {
    id: 'e_40', session_id: 's_review_now',
    actor_kind: 'user', actor_ref: 'self', action: 'review',
    subject_kind: 'question', subject_id: 'q4', outcome: 'success',
    payload: { fsrs_rating: 'good', fsrs_state_after: { due: NOW + 3 * DAY, stability: 4.2, state: 'review' } },
    caused_by_event_id: null,
    created_at: NOW - 4 * MIN,
  },
  {
    id: 'e_41', session_id: 's_review_now',
    actor_kind: 'user', actor_ref: 'self', action: 'review',
    subject_kind: 'question', subject_id: 'q2', outcome: 'failure',
    payload: { fsrs_rating: 'hard', fsrs_state_after: { due: NOW + 6 * HR, stability: 1.2, state: 'learning' } },
    caused_by_event_id: null,
    created_at: NOW - 2 * MIN,
  },

  // ── Ingestion (current SSE feed) ──────────────────────────
  {
    id: 'e_50', session_id: 's_ingest_now',
    actor_kind: 'user', actor_ref: 'self', action: 'import',
    subject_kind: 'source_document', subject_id: 'sd_001', outcome: 'success',
    payload: { filename: 'paper-p45.jpg', size_kb: 2840 },
    created_at: NOW - 12 * MIN,
  },
  {
    id: 'e_51', session_id: 's_ingest_now',
    actor_kind: 'agent', actor_ref: 'tencent_mark', action: 'extract',
    subject_kind: 'source_document', subject_id: 'sd_001', outcome: 'partial',
    payload: { layout_quality: 'partial', warnings: ['cloze 5 空 / 检出 3 sub'], structured_block_ids: ['b1','b2','b3'] },
    caused_by_event_id: 'e_50',
    task_run_id: 't_050', cost_micro_usd: 0,
    created_at: NOW - 10 * MIN,
  },

  // ── Rate events: user accepted note a_n_zhi yesterday ─────
  {
    id: 'e_60', session_id: null,
    actor_kind: 'user', actor_ref: 'self', action: 'rate',
    subject_kind: 'event', subject_id: 'e_05', outcome: 'success',
    payload: { rating: 'accept', user_note: '收藏，挺有用' },
    caused_by_event_id: null,
    created_at: NOW - 22 * HR,
  },
];

// ── learning_item — TODO/Goal layer, decoupled from event ──
const LEARNING_ITEMS = [
  { id: 'li1', title: '梳理「之」的所有用法',     knowledge_ids: ['k_xuci_zhi'],        status: 'in_progress', version: 2, created_at: NOW - 3 * DAY, source: 'user' },
  { id: 'li2', title: '把《师说》全文背下来',     knowledge_ids: ['k_juedu', 'k_shici'], status: 'pending',     version: 1, created_at: NOW - 5 * DAY, source: 'user' },
  { id: 'li3', title: '「于」的来源 vs 比较',     knowledge_ids: ['k_xuci_yu'],          status: 'done',        version: 3, created_at: NOW - 14 * DAY, completed_at: NOW - 7 * DAY, source: 'user' },
  { id: 'li4', title: '攻克"而"的转折/并列判别', knowledge_ids: ['k_xuci_er'],          status: 'pending',     version: 1, created_at: NOW - 6 * HR,  source: 'agent', proposed_by: 'dreaming' },
];

// ── Sample copilot conversation events for s_copilot ───────
// brief v2.1 §1.6: AI is an agent, not a chatbot. Conversation MUST show
// tool calls. Each tool-use lands as an event(action='experimental:tool_use',
// subject_kind='query') so it's auditable + linkable via caused_by.
const COPILOT_SEED_EVENTS = [
  // Turn 1 — user asks the data-grounded question
  {
    id: 'ec_01', session_id: 's_copilot',
    actor_kind: 'user', actor_ref: 'self', action: 'experimental:ask_copilot',
    subject_kind: 'event', subject_id: 's_copilot', outcome: null,
    payload: { text: '现在有哪些错题可以推荐？' },
    caused_by_event_id: null,
    created_at: NOW - 180,
  },
  // Turn 2 — Copilot reaches for a tool instead of guessing from chat memory
  {
    id: 'ec_02', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:tool_use',
    subject_kind: 'query', subject_id: 'tu_001', outcome: 'success',
    payload: {
      tool: 'query_mistakes',
      args: {
        filter: "outcome='failure' AND judge_status IS NULL",
        window: 'created_at > now() - 7d',
        limit: 10,
      },
      result_summary: '1 event found',
      result_data: [
        { event_id: 'e_20', question_id: 'q3', age: '12 分钟前', knowledge: ['k_xuci_yu'] },
      ],
    },
    caused_by_event_id: 'ec_01',
    task_run_id: 't_c02', cost_micro_usd: 800,
    created_at: NOW - 174,
  },
  // Turn 3 — Copilot replies citing the tool result (not its memory)
  {
    id: 'ec_03', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:explain',
    subject_kind: 'event', subject_id: 'ec_02', outcome: 'success',
    payload: {
      text_md: '近 7 天里有 1 道错答没归因——12 分钟前的 q3「青，取之于蓝，而青于蓝」中两个"于"的用法（挂在 k_xuci_yu）。\n\n建议先归因它，再决定要不要刷"于"的变式。两步都可以让我做。',
      referenced_event_ids: ['e_20'],
      referenced_knowledge_ids: ['k_xuci_yu'],
      // affordance: tool-call buttons that would write new events
      suggested_actions: [
        { label: '归因 e_20', tool: 'attribute_mistake', args: { event_id: 'e_20' } },
        { label: '出 3 道变式', tool: 'propose_variant', args: { question_id: 'q3', n: 3 } },
        { label: '打开 q3', nav: 'mistakes' },
      ],
    },
    caused_by_event_id: 'ec_02',
    task_run_id: 't_c03', cost_micro_usd: 4200,
    created_at: NOW - 170,
  },

  // Turn 4 — user accepts a chip (§1.6 #3b: chip is `accept_suggestion`,
  // not a fake user ask. UI renders as small chip-tag row.)
  {
    id: 'ec_04', session_id: 's_copilot',
    actor_kind: 'user', actor_ref: 'self', action: 'experimental:accept_suggestion',
    subject_kind: 'event', subject_id: 'ec_03', outcome: null,
    payload: { label: '出 3 道变式', tool: 'propose_variant', args: { question_id: 'q3', n: 3 } },
    caused_by_event_id: 'ec_03',
    created_at: NOW - 90,
  },
  // Turn 5 — Copilot calls the tool; tool itself writes the generate event
  {
    id: 'ec_05', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:tool_use',
    subject_kind: 'query', subject_id: 'tu_002', outcome: 'success',
    payload: {
      tool: 'propose_variant',
      args: { question_id: 'q3', n: 3, knowledge_id: 'k_xuci_yu' },
      result_summary: '3 variants generated',
      // tool actually wrote 3 generate events (artifacts) — refs here
      result_data: [
        { artifact_id: 'a_v_q3_2', title: '判断 · "于" 表来源还是比较' },
        { artifact_id: 'a_v_q3_3', title: '改写 · 把"于"全部替换为现代汉语' },
        { artifact_id: 'a_v_q3_4', title: '辨析 ·「于天下」「于囊中」「于蓝」三种"于"' },
      ],
      produced_event_ids: ['e_70', 'e_71', 'e_72'],
    },
    caused_by_event_id: 'ec_04',
    task_run_id: 't_c05', cost_micro_usd: 24400,
    created_at: NOW - 80,
  },
  // Turn 6 — short explain that surfaces the artifacts as accept/dismiss-able
  {
    id: 'ec_06', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:explain',
    subject_kind: 'event', subject_id: 'ec_05', outcome: 'success',
    payload: {
      text_md: '生成完了。第 1 道梯度最缓（2 选 1 判断），第 2 / 3 道递进。要全部加入复习队列，还是只挑一道？',
      referenced_event_ids: ['e_70', 'e_71', 'e_72'],
    },
    caused_by_event_id: 'ec_05',
    task_run_id: 't_c06', cost_micro_usd: 3100,
    created_at: NOW - 76,
  },

  // ── §1.6 #5 — Failed tool calls (soft fail + hard fail) ──
  // Turn 7 — user asks about review streak (soft-fail demo)
  {
    id: 'ec_07', session_id: 's_copilot',
    actor_kind: 'user', actor_ref: 'self', action: 'experimental:ask_copilot',
    subject_kind: 'event', subject_id: 'ec_06', outcome: null,
    payload: { text: '我最近 30 天的复习记录怎么样？' },
    caused_by_event_id: 'ec_06',
    created_at: NOW - 50,
  },
  // Turn 8 — SOFT FAIL: query returns 0 rows. tool succeeds, but result is empty.
  {
    id: 'ec_08', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:tool_use',
    subject_kind: 'query', subject_id: 'tu_003', outcome: 'success',
    payload: {
      tool: 'query_events',
      args: {
        filter: "action='review' AND outcome IN ('success','failure')",
        window: 'now() - 30d',
      },
      result_summary: '0 events found',
      result_data: [],
    },
    caused_by_event_id: 'ec_07',
    task_run_id: 't_c08', cost_micro_usd: 600,
    created_at: NOW - 46,
  },
  // Turn 9 — Copilot acknowledges empty result + offers a corrective chip
  {
    id: 'ec_09', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:explain',
    subject_kind: 'event', subject_id: 'ec_08', outcome: 'success',
    payload: {
      text_md: '近 30 天没有复习记录——你的第一次会话是今天，FSRS 还没积起数据。要不要看看更早是否有？',
      suggested_actions: [
        { label: '扩到 90 天再查', tool: 'query_events', args: { filter: "action='review'", window: 'now() - 90d' } },
        { label: '看所有 attempts', tool: 'query_events', args: { filter: "action='attempt'", window: 'now() - 90d' } },
      ],
    },
    caused_by_event_id: 'ec_08',
    task_run_id: 't_c09', cost_micro_usd: 2800,
    created_at: NOW - 42,
  },

  // Turn 10 — user wants a hard variant; this will hard-fail
  {
    id: 'ec_10', session_id: 's_copilot',
    actor_kind: 'user', actor_ref: 'self', action: 'experimental:ask_copilot',
    subject_kind: 'event', subject_id: 'ec_09', outcome: null,
    payload: { text: '给 q3 再来一道完整试卷级的多步推理题' },
    caused_by_event_id: 'ec_09',
    created_at: NOW - 28,
  },
  // Turn 11 — HARD FAIL: tool itself errors (timeout). outcome='failure'.
  {
    id: 'ec_11', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:tool_use',
    subject_kind: 'query', subject_id: 'tu_004', outcome: 'failure',
    payload: {
      tool: 'propose_variant',
      args: { question_id: 'q3', n: 1, complexity: 'paper_level' },
      result_summary: 'timeout after 30s',
      error_reason: 'timeout_30s',
      error_detail: 'sonnet-4 took >30s on paper_level prompt; haiku fallback also failed',
    },
    caused_by_event_id: 'ec_10',
    task_run_id: 't_c11', cost_micro_usd: 18000, // cost still charged on failure
    created_at: NOW - 18,
  },
  // Turn 12 — graceful degradation; no faking success
  {
    id: 'ec_12', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot', action: 'experimental:explain',
    subject_kind: 'event', subject_id: 'ec_11', outcome: 'success',
    payload: {
      text_md: '刚才生成超时了（sonnet-4 + haiku 双 fallback 都没出来，30s 超时）。多步推理题太长，要不要降一级试试？',
      suggested_actions: [
        { label: '重试同样难度', tool: 'propose_variant', args: { question_id: 'q3', n: 1, complexity: 'paper_level' } },
        { label: '降到中等难度', tool: 'propose_variant', args: { question_id: 'q3', n: 1, complexity: 'medium' } },
      ],
    },
    caused_by_event_id: 'ec_11',
    task_run_id: 't_c12', cost_micro_usd: 2400,
    created_at: NOW - 14,
  },
];

// ── Tool-emitted events for the conversation above ─────────
// These live in the main EVENTS table (mirroring real backend behavior:
// tool calls write events). Appended after EVENTS is defined below.
const COPILOT_TOOL_EMITTED_EVENTS = [
  {
    id: 'e_70', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot:propose_variant', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_v_q3_2', outcome: 'success',
    payload: {
      artifact_kind: 'variant',
      title: '判断 · "于" 表来源还是比较',
      body_md: '判断下列句中"于"是"来源(从)"还是"比较(比)"：\n① 学不可以已，青取之于蓝。\n② 苛政猛于虎也。',
      referenced_event_ids: ['e_20'],
    },
    caused_by_event_id: 'ec_05',
    task_run_id: 't_c05', cost_micro_usd: 8200,
    created_at: NOW - 79,
  },
  {
    id: 'e_71', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot:propose_variant', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_v_q3_3', outcome: 'success',
    payload: {
      artifact_kind: 'variant',
      title: '改写 · 把"于"全部替换为现代汉语',
      body_md: '把这一段里所有的"于"改写为相应的现代汉语介词或动词：「夫人之相与，俯仰一世；不慕权于天子，不贪利于市井，乃如其志」。',
      referenced_event_ids: ['e_20'],
    },
    caused_by_event_id: 'ec_05',
    task_run_id: 't_c05', cost_micro_usd: 8400,
    created_at: NOW - 78,
  },
  {
    id: 'e_72', session_id: 's_copilot',
    actor_kind: 'agent', actor_ref: 'copilot:propose_variant', action: 'generate',
    subject_kind: 'artifact', subject_id: 'a_v_q3_4', outcome: 'success',
    payload: {
      artifact_kind: 'variant',
      title: '辨析 · 三个"于"',
      body_md: '辨析「于天下」（《滕王阁序》）/「于囊中」（《廉颇蔺相如列传》）/「于蓝」（《劝学》）中三个"于"的不同用法。',
      referenced_event_ids: ['e_20'],
    },
    caused_by_event_id: 'ec_05',
    task_run_id: 't_c05', cost_micro_usd: 7800,
    created_at: NOW - 77,
  },
];

// Merge tool-emitted events into EVENTS list so EventChain can walk them.
EVENTS.push(...COPILOT_TOOL_EMITTED_EVENTS);

// Convenience: index events by id, by subject
function indexEvents(events) {
  const byId = {};
  const childrenOf = {}; // caused_by_event_id → [child events]
  const bySubject = {};  // `${kind}:${id}` → [events]
  for (const ev of events) {
    byId[ev.id] = ev;
    if (ev.caused_by_event_id) {
      (childrenOf[ev.caused_by_event_id] ||= []).push(ev);
    }
    const sk = `${ev.subject_kind}:${ev.subject_id}`;
    (bySubject[sk] ||= []).push(ev);
  }
  return { byId, childrenOf, bySubject };
}

Object.assign(window, {
  NOW, MIN, HR, DAY,
  KNOWLEDGE, KNOWLEDGE_EDGES, RELATION_TYPES, TOOLS,
  QUESTIONS, ARTIFACTS, SESSIONS,
  EVENTS, LEARNING_ITEMS, COPILOT_SEED_EVENTS,
  indexEvents,
});
